In [ ]:
import pandas as pd
import requests

In [ ]:
endpoint = 'https://data.cdc.gov/resource/x9gk-5huc.json'

In [ ]:
response=requests.get(endpoint)

In [ ]:
data=response.text

In [ ]:
df= pd.read_json(data)

In [ ]:
camp_df=df.loc[df['label']=='Campylobacteriosis']

In [ ]:
df.label.unique()

In [ ]:
endpoint2 = 'https://data.cdc.gov/resource/kxvg-q6s7.json'

In [ ]:
response1= requests.get(endpoint2)

In [ ]:
data2=response1.text

In [ ]:
df2=pd.read_json(data2)

In [ ]:
df2.loc[df2['mumps_current_week_flag'].isna()==False]

In [ ]:
endpoint3='https://data.cdc.gov/resource/fj6i-3v3k.json?$query=SELECT%20reporting_area%2C%20mmwr_year%2C%20mmwr_week%2C%20hepatitis_b_perinatal%2C%20hepatitis_b_perinatal_1%2C%20hepatitis_b_perinatal_2%2C%20hepatitis_b_perinatal_3%2C%20hepatitis_b_perinatal_4%2C%20hepatitis_b_perinatal_5%2C%20hepatitis_b_perinatal_6%2C%20hepatitis_b_perinatal_7%2C%20hepatitis_c_acute_confirmed%2C%20hepatitis_c_acute_confirmed_1%2C%20hepatitis_c_acute_confirmed_2%2C%20hepatitis_c_acute_previous%2C%20hepatitis_c_acute_confirmed_3%2C%20hepatitis_c_acute_confirmed_4%2C%20hepatitis_c_acute_confirmed_5%2C%20hepatitis_c_acute_confirmed_6%2C%20hepatitis_c_acute_probable%2C%20hepatitis_c_acute_probable_1%2C%20hepatitis_c_acute_probable_2%2C%20hepatitis_c_acute_probable_3%2C%20hepatitis_c_acute_probable_4%2C%20hepatitis_c_acute_probable_5%2C%20hepatitis_c_acute_probable_6%2C%20hepatitis_c_acute_probable_7%2C%20location_1%2C%20location_2%2C%20reporting_area_sort%2C%20tableoneq%20ORDER%20BY%20reporting_area_sort%20ASC'

In [ ]:
response2=requests.get(endpoint3)

In [ ]:
data3=response2.text

In [ ]:
hep_df3=pd.read_json(data3)

In [ ]:
hep_df3

In [ ]:
endpoint4='https://data.cdc.gov/resource/vq7a-fvin.json?$query=SELECT%20reporting_area%2C%20mmwr_year%2C%20mmwr_week%2C%20vibriosis_any_species_of%2C%20vibriosis_any_species_of_1%2C%20vibriosis_any_species_of_2%2C%20vibriosis_any_species_of_3%2C%20vibriosis_any_species_of_4%2C%20vibriosis_any_species_of_5%2C%20vibriosis_any_species_of_6%2C%20vibriosis_any_species_of_7%2C%20vibriosis_any_species_of_8%2C%20vibriosis_any_species_of_9%2C%20vibriosis_any_species_of_10%2C%20vibriosis_any_species_of_11%2C%20vibriosis_any_species_of_12%2C%20vibriosis_any_species_of_13%2C%20vibriosis_any_species_of_14%2C%20vibriosis_any_species_of_15%2C%20location_1%2C%20location_2%2C%20reporting_area_sort%2C%20tableonell%20ORDER%20BY%20reporting_area_sort%20ASC'

In [ ]:
response4=requests.get(endpoint4)

In [ ]:
data_vib=response4.text

In [ ]:
df_vib=pd.read_json(data_vib)

In [ ]:
df_vib

In [ ]:
vax_endpoint='https://data.cdc.gov/resource/ee48-w5t6.json'

In [ ]:
response_vax=requests.get(vax_endpoint)

In [ ]:
data_vax=response_vax.text

In [ ]:
df_vax=pd.read_json(data_vax)

In [ ]:
df_vax

ADULT VAX DATA ________

In [ ]:
adult_vax=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/Adult_vax.csv')

In [ ]:
adult_vax.loc[adult_vax['Survey Year']==2018].Vaccine.unique()

In [ ]:
pne_vax_2018=adult_vax.loc[(adult_vax['Survey Year']==2018)&(adult_vax['Vaccine']=='Pneumococcal')&(adult_vax['Geography Type']=='States/Local Areas')&(adult_vax['Dimension']=='Overall')&(adult_vax['Dimension Type']=='>=65 Years')]

In [ ]:
pne_vax_2018=pne_vax_2018[['Geography', 'Estimate (%)']]

In [ ]:
pne_vax_2018=pne_vax_2018.rename(columns={'Geography':'State', 'Estimate (%)':'Percentage_Pneumococcal'})

In [ ]:
pne_vax_2018.to_csv('pne_vax_2018.csv')

In [ ]:
pne_vax_2018_f=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/pne_vax_2018.csv')

In [ ]:
pne_vax_2018_f=pne_vax_2018_f.drop(columns=['Unnamed: 0'])

In [ ]:
pne_vax_2018_f

ADOLESCENT VAX DATA _______

In [ ]:
ado_2018['Vaccine/Sample'].unique()

In [ ]:
ado_vax=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/Adolescent_Vax-13-17.csv')

In [ ]:
ado_2018=ado_vax.loc[ado_vax['Survey Year']=='2018']

In [ ]:
ado_mmr_2018=ado_2018.loc[ado_2018['Vaccine/Sample']=='MMR']

In [ ]:
ado_mmr_2018.to_csv('adolescent_mmr_2018.csv')

In [ ]:
ado_vax.loc[(ado_vax['Survey Year']=='2020')&(ado_vax['Geography']=='Tennessee')]

In [ ]:
ado_vax.loc[(ado_vax['Vaccine/Sample']=='HPV')&(ado_vax['Survey Year']=='2020')&(ado_vax['Dose']=='Up-to-Date, Males and Females'), ('Geography', 'Dimension', 'Estimate (%)')]

In [ ]:
ado_mmr_2018_f=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/adolescent_mmr_2018.csv')

In [ ]:
ado_mmr_2018_f=ado_mmr_2018_f.drop(columns=['Unnamed: 0', 'Dimension Type', 'Geography Type', 'Dose'])

In [ ]:
ado_mmr_2018_f=ado_mmr_2018_f.rename(columns={'Geography':'State', 'Estimate (%)':'Percentage_MMR', 'Sample Size':'sample_size_mmr'})

In [ ]:
ado_mmr_2018_f=ado_mmr_2018_f[['State', 'Percentage_MMR']]

In [ ]:
hpv_vax_2018=ado_2018.loc[ado_2018['Vaccine/Sample']=='HPV']

In [ ]:
hpv_vax_2018=hpv_vax_2018.loc[hpv_vax_2018['Dose']=='Up-to-Date, Males and Females']

In [ ]:
hpv_vax_2018=hpv_vax_2018[['Geography', 'Estimate (%)']]

In [ ]:
hpv_vax_2018=hpv_vax_2018.rename(columns={'Geography':'State', 'Estimate (%)': 'Percentage_HPV'})

In [ ]:
hpv_vax_2018.to_csv('hpv_vax_2018.csv')

In [ ]:
hpv_vax_2018_f=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/hpv_vax_2018.csv')

In [ ]:
hpv_vax_2018_f=hpv_vax_2018_f.drop(columns=['Unnamed: 0'])

In [ ]:
hepb_vax_2018=ado_2018.loc[ado_2018['Vaccine/Sample']=='HepB']

In [ ]:
hepb_vax_2018[['Geography', 'Estimate (%)']].to_csv('hepb_vax_2018.csv')

In [ ]:
hepb_vax_2018_f=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/hepb_vax_2018.csv')

In [ ]:
hepb_vax_2018_f=hepb_vax_2018_f.drop(columns=['Unnamed: 0'])

In [ ]:
hepb_vax_2018_f=hepb_vax_2018_f.rename(columns={'Geography':'State', 'Estimate (%)':'Percentage_HepB'})

In [ ]:
hepb_vax_2018_f

In [330]:
hpv_vax_2021=ado_vax.loc[(ado_vax['Survey Year']=='2021')&(ado_vax['Vaccine/Sample']=='HPV')&(ado_vax['Dose']=='Up-to-Date, Males and Females')&(ado_vax['Dimension']=='13-17 Years'), ('Geography', 'Estimate (%)')]

In [332]:
hpv_vax_2021.to_csv('hpv_vax_2021.csv')

In [333]:
hpv_vax_2021_f=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/hpv_vax_2021.csv')

In [335]:
hpv_vax_2021_f=hpv_vax_2021_f.drop(columns=['Unnamed: 0'])

In [337]:
hpv_vax_2021_f=hpv_vax_2021_f.rename(columns={'Geography':'State', 'Estimate (%)':'Percentage_HPV'})

In [342]:
hepb_vax_2021=ado_vax.loc[(ado_vax['Survey Year']=='2021')&(ado_vax['Vaccine/Sample']=='HepB'), ('Geography', 'Estimate (%)')]

In [343]:
hepb_vax_2021.to_csv('hepb_vax_2021.csv')

In [344]:
hepb_vax_2021_f=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/hepb_vax_2021.csv')

In [346]:
hepb_vax_2021_f=hepb_vax_2021_f.drop(columns=['Unnamed: 0'])

In [347]:
hepb_vax_2021_f=hepb_vax_2021_f.rename(columns={'Geography':'State', 'Estimate (%)':'Percentage_HepB'})

In [348]:
hepb_vax_2021_f

   State  Percentage_HepB
0     AL             92.4
1     AK             90.5
2     AZ             86.2
3     AR             94.1
4     CA             90.5
5     CO             93.8
6     CT             96.4
7     DE             91.0
8     DC             85.6
9     FL             95.7
10    GA             95.9
11    GU             81.8
12    HI             93.8
13    ID             90.8
14    IL             96.1
15    IN             92.9
16    IA             97.6
17    KS             93.1
18    KY             94.9
19    LA             91.8
20    ME             92.5
21    MD             93.2
22    MA             95.9
23    MI             90.6
24    MN             96.1
25    MS             91.0
26    MO             90.7
27    MT             91.2
28    NE             92.9
29    NV             89.9
30    NH             96.9
31    NJ             91.5
32    NM             88.0
33    NY             96.2
34    NC             95.5
35    ND             93.1
36    OH             94.1
37    OK             90.4
38    OR             92.7
39    PA             92.6
40    PR             84.0
41    US             92.3
42    RI             96.3
43    SC             95.0
44    SD             97.2
45    TN             95.1
46    TX             84.4
47    UT             94.3
48    VT             94.1
49    VA             92.2
50    WA             90.6
51    WV             86.1
52    WI             95.2
53    WY             89.1

In [352]:
mmr_vax_2021=ado_vax.loc[(ado_vax['Survey Year']=='2021')&(ado_vax['Vaccine/Sample']=='MMR'), ('Geography', 'Estimate (%)')]

In [353]:
mmr_vax_2021=mmr_vax_2021.rename(columns={'Geography':'State', 'Estimate (%)':'Percentage_MMR'})

In [355]:
mmr_vax_2021.to_csv('mmr_vax_2021.csv')

In [356]:
mmr_vax_2021_f=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/mmr_vax_2021.csv')

In [358]:
mmr_vax_2021_f=mmr_vax_2021_f.drop(columns=['Unnamed: 0'])

In [572]:
adult_vax.Vaccine.unique()

array(['Pneumococcal', 'Tdap', 'Td or Tdap', 'Zoster (Shingles)'],
      dtype=object)

In [573]:
pne_vax=adult_vax.loc[adult_vax.Vaccine=='Pneumococcal']

In [574]:
pne_vax21=pne_vax.loc[pne_vax['Survey Year']==2021]

In [576]:
pne_vax21=adult_vax.loc[(adult_vax['Survey Year']==2021)&(adult_vax['Vaccine']=='Pneumococcal')&(adult_vax['Geography Type']=='States/Local Areas')&(adult_vax['Dimension']=='Overall')&(adult_vax['Dimension Type']=='>=65 Years')]

In [580]:
pne_vax21=pne_vax21[['Geography','Estimate (%)']]

In [582]:
pne_vax21.to_csv('pne_vax21.csv')

In [583]:
pne_vax21_f=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/data/pne_vax21.csv')

In [586]:
pne_vax21_f=pne_vax21_f.drop(columns=['Unnamed: 0'])

In [588]:
pne_vax21_f=pne_vax21_f.rename(columns={'Geography':'State', 'Estimate (%)':'Percent_pneumococcal'})

In [591]:
vax_df=mmr_vax_2021_f.merge(pne_vax21_f, how='inner', on='State')

In [593]:
vax_df=vax_df.merge(hepb_vax_2021_f, how='inner', on='State')

In [595]:
vax_df=vax_df.merge(hpv_vax_2021_f, how='inner', on='State')

In [596]:
vax_df

,State,Percentage_MMR,Percent_pneumococcal,Percentage_HepB,Percentage_HPV
0,AL,95.8,70.1,92.4,62.5
1,AK,91.8,64.4,90.5,56.2
2,AZ,86.4,69.1,86.2,61.7
3,AR,94.0,70.7,94.1,56.8
4,CA,89.3,65.4,90.5,69.0
5,CO,95.6,76.3,93.8,69.2
6,CT,96.2,72.9,96.4,66.4
7,DE,92.5,72.8,91.0,68.9
8,DC,87.8,72.2,85.6,79.4
9,FL,95.2,NaN,95.7,49.0
10,GA,95.5,70.2,95.9,60.9
11,GU,78.7,26.9,81.8,54.0
12,HI,91.6,60.4,93.8,69.3
13,ID,89.2,68.3,90.8,61.6
14,IL,96.0,70.9,96.1,62.2
15,IN,92.5,73.1,92.9,55.2
16,IA,97.7,75.4,97.6,66.1
17,KS,94.6,74.4,93.1,64.3
18,KY,94.6,65.9,94.9,57.0
19,LA,94.1,69.5,91.8,63.9
20,ME,94.9,72.4,92.5,61.5
21,MD,94.8,74.4,93.2,71.9
22,MA,97.0,71.2,95.9,75.0
23,MI,88.9,72.0,90.6,64.7
24,MN,95.2,71.0,96.1,65.7
25,MS,92.3,63.2,91.0,32.7
26,MO,88.3,72.9,90.7,59.3
27,MT,94.2,69.3,91.2,52.6
28,NE,94.0,75.3,92.9,61.9
29,NV,90.3,64.3,89.9,56.5
30,NH,97.2,75.1,96.9,72.3
31,NJ,90.0,64.2,91.5,54.8
32,NM,88.1,68.6,88.0,57.9
33,NY,94.2,65.6,96.2,64.4
34,NC,95.3,75.2,95.5,67.8
35,ND,98.3,70.4,93.1,72.2
36,OH,95.0,70.7,94.1,62.2
37,OK,91.8,75.3,90.4,56.7
38,OR,92.4,75.5,92.7,67.0
39,PA,92.7,70.3,92.6,68.7
40,PR,80.9,34.1,84.0,67.2
41,RI,94.8,74.6,96.3,83.2
42,SC,95.3,70.9,95.0,62.1
43,SD,98.0,74.2,97.2,74.7
44,TN,95.1,69.9,95.1,56.5
45,TX,84.1,69.0,84.4,51.5
46,UT,93.1,73.4,94.3,61.4
47,VT,97.1,70.6,94.1,66.7
48,VA,94.8,75.0,92.2,64.9
49,WA,93.2,75.4,90.6,67.8
50,WV,87.6,72.0,86.1,56.4
51,WI,98.6,71.8,95.2,63.3
52,WY,91.3,66.8,89.1,48.0

In [ ]:
pne_vax21.loc[pne_vax21['Geography']=='Tennessee']

In [360]:
pubschool=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/pubschool.csv')

C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2297661209.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  pubschool=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/pubschool.csv')

In [363]:
pubschool

,X,Y,OBJECTID,NCESSCH,SURVYEAR,STABR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,...,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD
0,-86.206200,34.260200,1,10000500870,2020-2021,AL,100005,AL-101,Albertville City,Albertville Middle School,...,230.0,469.0,19.0,10.0,29.0,187.0,184.0,371.0,34.260200,-86.206200
1,-86.204900,34.262200,2,10000500871,2020-2021,AL,100005,AL-101,Albertville City,Albertville High School,...,371.0,785.0,17.0,21.0,38.0,368.0,338.0,706.0,34.262200,-86.204900
2,-86.220100,34.273300,3,10000500879,2020-2021,AL,100005,AL-101,Albertville City,Albertville Intermediate School,...,253.0,481.0,17.0,12.0,29.0,177.0,168.0,345.0,34.273300,-86.220100
3,-86.221806,34.252700,4,10000500889,2020-2021,AL,100005,AL-101,Albertville City,Albertville Elementary School,...,237.0,497.0,7.0,8.0,15.0,180.0,160.0,340.0,34.252700,-86.221806
4,-86.193300,34.289800,5,10000501616,2020-2021,AL,100005,AL-101,Albertville City,Albertville Kindergarten and PreK,...,137.0,288.0,6.0,7.0,13.0,108.0,108.0,216.0,34.289800,-86.193300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100717,-64.917602,18.341950,100718,780003000024,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,LOCKHART ELEMENTARY SCHOOL,...,29.0,59.0,1.0,1.0,2.0,2.0,4.0,6.0,18.341950,-64.917602
100718,-64.952483,18.338742,100719,780003000026,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,ULLA F MULLER ELEMENTARY SCHOOL,...,34.0,64.0,2.0,1.0,3.0,4.0,5.0,9.0,18.338742,-64.952483
100719,-64.899024,18.354782,100720,780003000027,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,YVONNE BOWSKY ELEMENTARY SCHOOL,...,25.0,57.0,NaN,NaN,NaN,6.0,3.0,9.0,18.354782,-64.899024
100720,-64.945940,18.336658,100721,780003000033,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,CANCRYN JUNIOR HIGH SCHOOL,...,72.0,153.0,1.0,NaN,1.0,7.0,11.0,18.0,18.336658,-64.945940
100721,-64.890311,18.318230,100722,780003000034,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,BERTHA BOSCHULTE JUNIOR HIGH,...,30.0,55.0,NaN,NaN,NaN,1.0,1.0,2.0,18.318230,-64.890311

In [383]:
pubschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False)

,X,Y,OBJECTID,NCESSCH,SURVYEAR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,LSTREET1,...,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD
STABR,,,,,,,,,,,,,,,,,,,,,
CA,10330,10330,10330,10330,10330,10330,10330,10330,10330,10330,...,10116,10128,9356,9352,9699,9840,9812,9984,10330,10330
TX,9467,9467,9467,9467,9467,9467,9467,9467,9467,9467,...,8997,8997,8997,8997,8997,8997,8997,8997,9467,9467
NY,4831,4831,4831,4831,4831,4831,4831,4831,4831,4831,...,4710,4766,4135,4149,4435,4673,4624,4752,4831,4831
IL,4384,4384,4384,4384,4384,4384,4384,4384,4384,4384,...,3599,3722,3397,3357,3597,3626,3609,3685,4384,4384
FL,4267,4267,4267,4267,4267,4267,4267,4267,4267,4267,...,4213,4213,4213,4213,4213,4213,4213,4213,4267,4267
MI,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,...,3526,3526,3526,3526,3526,3526,3526,3526,3553,3553
OH,3532,3532,3532,3532,3532,3532,3532,3532,3532,3532,...,3531,3531,3531,3531,3531,3531,3531,3531,3532,3532
PA,2952,2952,2952,2952,2952,2952,2952,2952,2952,2952,...,2946,2946,2946,2946,2946,2946,2946,2946,2952,2952
NC,2730,2730,2730,2730,2730,2730,2730,2730,2730,2730,...,2679,2679,2679,2679,2679,2679,2679,2679,2730,2730
NJ,2566,2566,2566,2566,2566,2566,2566,2566,2566,2566,...,2527,2541,2140,2140,2262,2469,2452,2500,2566,2566
MN,2542,2542,2542,2542,2542,2542,2542,2542,2542,2542,...,2353,2444,2327,2282,2387,2471,2461,2489,2542,2542
WA,2507,2507,2507,2507,2507,2507,2507,2507,2507,2507,...,2465,2487,2382,2379,2433,2495,2490,2500,2507,2507
AZ,2480,2480,2480,2480,2480,2480,2480,2480,2480,2480,...,2350,2350,2350,2350,2350,2350,2350,2350,2480,2480
MO,2460,2460,2460,2460,2460,2460,2460,2460,2460,2460,...,2102,2242,2035,2040,2141,2410,2408,2420,2460,2460
GA,2311,2311,2311,2311,2311,2311,2311,2311,2311,2311,...,2307,2307,2307,2307,2307,2307,2307,2307,2311,2311
WI,2258,2258,2258,2258,2258,2258,2258,2258,2258,2258,...,2125,2198,2054,2073,2162,2206,2199,2215,2258,2258
VA,2130,2130,2130,2130,2130,2130,2130,2130,2130,2130,...,2118,2118,2118,2118,2118,2118,2118,2118,2130,2130
CO,1927,1927,1927,1927,1927,1927,1927,1927,1927,1927,...,1911,1913,1733,1734,1815,1913,1911,1917,1927,1927
IN,1902,1902,1902,1902,1902,1902,1902,1902,1902,1902,...,1843,1885,1850,1841,1880,1894,1885,1899,1902,1902
TN,1880,1880,1880,1880,1880,1880,1880,1880,1880,1880,...,1796,1843,1718,1708,1785,1837,1813,1856,1880,1880
MA,1845,1845,1845,1845,1845,1845,1845,1845,1845,1845,...,1810,1829,1750,1723,1797,1832,1827,1837,1845,1845
OK,1790,1790,1790,1790,1790,1790,1790,1790,1790,1790,...,1698,1753,1789,1787,1789,1783,1779,1783,1790,1790
AL,1559,1559,1559,1559,1559,1559,1559,1559,1559,1559,...,1347,1347,1347,1347,1347,1347,1347,1347,1559,1559
KY,1532,1532,1532,1532,1532,1532,1532,1532,1532,1532,...,1465,1500,1445,1444,1486,1524,1523,1529,1532,1532
MD,1421,1421,1421,1421,1421,1421,1421,1421,1421,1421,...,1383,1409,1315,1304,1362,1378,1380,1404,1421,1421
LA,1354,1354,1354,1354,1354,1354,1354,1354,1354,1354,...,1280,1310,1235,1240,1298,1313,1296,1323,1354,1354
KS,1310,1310,1310,1310,1310,1310,1310,1310,1310,1310,...,1253,1282,1169,1176,1229,1310,1310,1310,1310,1310
IA,1309,1309,1309,1309,1309,1309,1309,1309,1309,1309,...,1250,1285,1184,1149,1242,1309,1309,1309,1309,1309
SC,1280,1280,1280,1280,1280,1280,1280,1280,1280,1280,...,1266,1266,1266,1266,1266,1266,1266,1266,1280,1280
OR,1263,1263,1263,1263,1263,1263,1263,1263,1263,1263,...,1263,1263,1263,1263,1263,1263,1263,1263,1263,1263
UT,1113,1113,1113,1113,1113,1113,1113,1113,1113,1113,...,1023,1034,948,939,975,1043,1040,1045,1113,1113
NE,1086,1086,1086,1086,1086,1086,1086,1086,1086,1086,...,1009,1009,1009,1009,1009,1009,1009,1009,1086,1086
AR,1080,1080,1080,1080,1080,1080,1080,1080,1080,1080,...,1042,1061,927,912,981,1066,1057,1068,1080,1080
MS,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,...,905,960,932,929,976,1001,1003,1019,1042,1042
CT,1001,1001,1001,1001,1001,1001,1001,1001,1001,1001,...,998,1000,977,964,992,998,998,1001,1001,1001
NM,886,886,886,886,886,886,886,886,886,886,...,873,879,573,565,645,844,835,856,886,886
PR,849,849,849,849,849,849,849,849,849,849,...,841,841,0,0,0,147,132,227,849,849
MT,829,829,829,829,829,829,829,829,829,829,...,826,826,826,826,826,826,826,826,829,829
ID,791,791,791,791,791,791,791,791,791,791,...,772,772,772,772,772,772,772,772,791,791
NV,754,754,754,754,754,754,754,754,754,753,...,720,720,720,720,720,720,720,720,754,754
SD,722,722,722,722,722,722,722,722,722,722,...,706,706,706,706,706,706,706,706,722,722
WV,711,711,711,711,711,711,711,711,711,711,...,411,496,539,527,594,672,663,672,711,711
ME,602,602,602,602,602,602,602,602,602,602,...,436,500,442,447,492,568,568,568,602,602
ND,531,531,531,531,531,531,531,531,531,531,...,394,426,342,349,394,474,472,476,531,531
AK,509,509,509,509,509,509,509,509,509,509,...,503,503,503,503,503,503,503,503,509,509
NH,496,496,496,496,496,496,496,496,496,496,...,416,447,403,406,436,496,496,496,496,496
WY,364,364,364,364,364,364,364,364,364,364,...,364,364,364,364,364,364,364,364,364,364
RI,314,314,314,314,314,314,314,314,314,314,...,301,305,298,292,304,305,305,306,314,314
VT,305,305,305,305,305,305,305,305,305,305,...,248,278,223,227,247,305,305,305,305,305
HI,295,295,295,295,295,295,295,295,295,295,...,293,294,294,294,294,286,279,287,295,295
DC,235,235,235,235,235,235,235,235,235,235,...,216,228,152,151,171,146,138,160,235,235
DE,230,230,230,230,230,230,230,230,230,228,...,221,225,217,215,220,225,224,225,230,230
BI,174,174,174,174,174,174,174,174,174,174,...,4,4,4,4,4,4,4,4,174,174
GU,44,44,44,44,44,44,44,44,44,44,...,41,41,41,41,41,41,41,41,44,44
MP,35,35,35,35,35,35,35,35,35,35,...,0,0,0,0,0,0,0,0,35,35
AS,29,29,29,29,29,29,29,29,29,29,...,1,3,0,0,0,3,5,6,29,29
VI,23,23,23,23,23,23,23,23,23,23,...,22,22,10,11,14,18,19,21,23,23

In [384]:
percent_elem=(round(elem_schools.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME/(pubschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME)*100, 3).reset_index())

In [385]:
percent_elem=percent_elem.rename(columns={'STABR':'State', 'SCH_NAME':'Percent_elem'})

In [386]:
percent_elem

   State  Percent_elem
0     AK        33.792
1     AL        45.093
2     AR        47.685
3     AS        79.310
4     AZ        48.669
5     BI        62.069
6     CA        57.783
7     CO        54.229
8     CT        60.340
9     DC        60.851
10    DE        51.739
11    FL        52.144
12    GA        56.772
13    GU        61.364
14    HI        62.373
15    IA        52.101
16    ID        49.052
17    IL        53.490
18    IN        55.521
19    KS        55.267
20    KY        47.258
21    LA        53.250
22    MA        57.073
23    MD        62.562
24    ME        58.638
25    MI        46.665
26    MN        38.749
27    MO        49.715
28    MP        25.714
29    MS        42.418
30    MT        51.628
31    NC        54.396
32    ND        51.224
33    NE        49.816
34    NH        57.460
35    NJ        58.418
36    NM        51.580
37    NV        56.499
38    NY        53.053
39    OH        50.340
40    OK        52.179
41    OR        56.453
42    PA        55.556
43    PR        60.895
44    RI        55.732
45    SC        54.062
46    SD        45.429
47    TN        54.468
48    TX        49.741
49    UT        56.244
50    VA        53.850
51    VI        65.217
52    VT        68.197
53    WA        48.664
54    WI        50.000
55    WV        57.806
56    WY        53.297

In [ ]:
elem_schools=pubschool.loc[pubschool['SCHOOL_LEVEL']=='Elementary']

In [ ]:
highschool=pubschool.loc[pubschool['SCHOOL_LEVEL']=='High']

In [600]:
highschool

,X,Y,OBJECTID,NCESSCH,SURVYEAR,STABR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,...,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD
1,-86.204900,34.262200,2,10000500871,2020-2021,AL,100005,AL-101,Albertville City,Albertville High School,...,371.0,785.0,17.0,21.0,38.0,368.0,338.0,706.0,34.262200,-86.204900
7,-86.142000,34.362500,8,10000600872,2020-2021,AL,100006,AL-048,Marshall County,Asbury High School,...,160.0,285.0,1.0,2.0,3.0,182.0,146.0,328.0,34.362500,-86.142000
10,-86.319462,34.178658,11,10000600878,2020-2021,AL,100006,AL-048,Marshall County,Douglas High School,...,119.0,255.0,2.0,3.0,5.0,203.0,177.0,380.0,34.178658,-86.319462
12,-86.253261,34.534948,13,10000600883,2020-2021,AL,100006,AL-048,Marshall County,Kate D Smith DAR High School,...,5.0,14.0,6.0,1.0,7.0,225.0,180.0,405.0,34.534948,-86.253261
15,-86.285900,34.305400,16,10000600987,2020-2021,AL,100006,AL-048,Marshall County,Marshall Technical School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.305400,-86.285900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100698,-66.399500,18.431900,100699,720003002085,2020-2021,PR,7200030,PR-01,PUERTO RICO DEPARTMENT OF EDUCATION,JUAN QUIRINDONGO MORELL (SUPERIOR),...,256.0,499.0,NaN,NaN,NaN,NaN,NaN,NaN,18.431900,-66.399500
100704,-64.798638,17.722947,100705,780000200013,2020-2021,VI,7800002,VI-002,Saint Croix School District,ST. CROIX EDUCATIONAL COMPEX HIGH SCHOOL,...,97.0,183.0,NaN,1.0,1.0,4.0,2.0,6.0,17.722947,-64.798638
100709,-64.780456,17.725655,100710,780000200030,2020-2021,VI,7800002,VI-002,Saint Croix School District,SAINT CROIX CENTRAL HIGH,...,142.0,277.0,1.0,4.0,5.0,4.0,NaN,4.0,17.725655,-64.780456
100711,-64.918749,18.342037,100712,780003000005,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,CHARLOTTE AMALIE HIGH SCHOOL,...,88.0,170.0,1.0,6.0,7.0,11.0,10.0,21.0,18.342037,-64.918749
100712,-64.853909,18.324876,100713,780003000015,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,IVANNA EUDORA KEAN HIGH SCHOOL,...,21.0,57.0,1.0,3.0,4.0,2.0,1.0,3.0,18.324876,-64.853909

In [ ]:
percent_high=(round(highschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME/(pubschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME)*100, 3).reset_index())

In [ ]:
percent_high=percent_high.rename(columns={'STABR':'State', 'SCH_NAME':'Percent_High'})

In [ ]:
percent_high

In [ ]:
highschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False)

In [ ]:
midschool=pubschool.loc[pubschool['SCHOOL_LEVEL']=='Middle']

In [ ]:
midschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False)

In [ ]:
percent_mid=(round(midschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME/(pubschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME)*100, 3).reset_index())

In [ ]:
percent_mid=percent_mid.rename(columns={'STABR':'State', 'SCH_NAME':'Percent_mid'})

In [ ]:
percent_mid

In [ ]:
school_perc=percent_elem.merge(percent_high, how='outer', on='State')

In [ ]:
school_perc=school_perc.merge(percent_mid, how='outer', on='State')

In [ ]:
school_perc['Percent_unaccounted']=(100-(school_perc.Percent_elem+school_perc.Percent_High+school_perc.Percent_mid))

In [430]:
school_perc

   State  Percent_elem  Percent_High  Percent_mid  Percent_unaccounted
0     AK        33.792        15.324        7.466               43.418
1     AL        45.093        26.235       16.485               12.187
2     AR        47.685        27.870       19.352                5.093
3     AS        79.310        20.690          NaN                  NaN
4     AZ        48.669        30.323        9.355               11.653
5     BI        62.069        12.644        2.874               22.413
6     CA        57.783        21.607       13.650                6.960
7     CO        54.229        22.574       14.946                8.251
8     CT        60.340        19.680       17.882                2.098
9     DC        60.851        17.021       17.447                4.681
10    DE        51.739        18.261       16.087               13.913
11    FL        52.144        22.170       13.780               11.906
12    GA        56.772        19.602       20.640                2.986
13    GU        61.364        15.909       20.455                2.272
14    HI        62.373        14.576       14.237                8.814
15    IA        52.101        25.745       19.099                3.055
16    ID        49.052        25.917       14.412               10.619
17    IL        53.490        21.852       16.423                8.235
18    IN        55.521        21.504       17.403                5.572
19    KS        55.267        26.183       17.099                1.451
20    KY        47.258        28.851       14.360                9.531
21    LA        53.250        20.384       16.691                9.675
22    MA        57.073        20.108       17.507                5.312
23    MD        62.562        16.890       16.115                4.433
24    ME        58.638        19.601       14.120                7.641
25    MI        46.665        28.202       14.298               10.835
26    MN        38.749        36.310       12.628               12.313
27    MO        49.715        26.992       16.138                7.155
28    MP        25.714        17.143       14.286               42.857
29    MS        42.418        30.326       17.850                9.406
30    MT        51.628        20.869       27.141                0.362
31    NC        54.396        21.575       17.802                6.227
32    ND        51.224        31.073        7.910                9.793
33    NE        49.816        24.770       11.786               13.628
34    NH        57.460        19.153       20.161                3.226
35    NJ        58.418        18.862       16.758                5.962
36    NM        51.580        24.718       18.510                5.192
37    NV        56.499        19.629       15.517                8.355
38    NY        53.053        24.488       16.746                5.713
39    OH        50.340        25.510       18.658                5.492
40    OK        52.179        26.089       20.391                1.341
41    OR        56.453        21.219       16.152                6.176
42    PA        55.556        24.289       17.751                2.404
43    PR        60.895        23.086       11.072                4.947
44    RI        55.732        20.701       18.790                4.777
45    SC        54.062        22.656       19.609                3.673
46    SD        45.429        27.008       23.407                4.156
47    TN        54.468        21.489       18.989                5.054
48    TX        49.741        19.436       18.517               12.306
49    UT        56.244        17.610       12.668               13.478
50    VA        53.850        15.258       16.291               14.601
51    VI        65.217        17.391       13.043                4.349
52    VT        68.197        20.656        8.525                2.622
53    WA        48.664        26.047       15.078               10.211
54    WI        50.000        24.889       17.848                7.263
55    WV        57.806        22.644       15.612                3.938
56    WY        53.297        24.725       16.758                5.220

In [366]:
pubschool1920=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/Public_School_Characteristics_2019-20.csv')

In [368]:
pubschool1920.groupby('STABR').count().sort_values('SCH_NAME', ascending=False)

,X,Y,OBJECTID,NCESSCH,SURVYEAR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,LSTREET1,...,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD
STABR,,,,,,,,,,,,,,,,,,,,,
CA,10381,10381,10381,10381,10381,10381,10381,10381,10381,10381,...,10381,10381,10381,10381,10381,10381,10381,10381,10381,10381
TX,9425,9425,9425,9425,9425,9425,9425,9425,9425,9425,...,9425,9425,9425,9425,9425,9425,9425,9425,9425,9425
NY,4833,4833,4833,4833,4833,4833,4833,4833,4833,4833,...,4833,4833,4833,4833,4833,4833,4833,4833,4833,4833
IL,4351,4351,4351,4351,4351,4351,4351,4351,4351,4351,...,4351,4351,4351,4351,4351,4351,4351,4351,4351,4351
FL,4244,4244,4244,4244,4244,4244,4244,4244,4244,4244,...,4244,4244,4244,4244,4244,4244,4244,4244,4244,4244
MI,3562,3562,3562,3562,3562,3562,3562,3562,3562,3562,...,3562,3562,3562,3562,3562,3562,3562,3562,3562,3562
OH,3539,3539,3539,3539,3539,3539,3539,3539,3539,3539,...,3539,3539,3539,3539,3539,3539,3539,3539,3539,3539
PA,2960,2960,2960,2960,2960,2960,2960,2960,2960,2960,...,2960,2960,2960,2960,2960,2960,2960,2960,2960,2960
NC,2704,2704,2704,2704,2704,2704,2704,2704,2704,2704,...,2704,2704,2704,2704,2704,2704,2704,2704,2704,2704
MN,2586,2586,2586,2586,2586,2586,2586,2586,2586,2586,...,2586,2586,2586,2586,2586,2586,2586,2586,2586,2586
NJ,2566,2566,2566,2566,2566,2566,2566,2566,2566,2566,...,2566,2566,2566,2566,2566,2566,2566,2566,2566,2566
WA,2475,2475,2475,2475,2475,2475,2475,2475,2475,2475,...,2475,2475,2475,2475,2475,2475,2475,2475,2475,2475
MO,2456,2456,2456,2456,2456,2456,2456,2456,2456,2456,...,2456,2456,2456,2456,2456,2456,2456,2456,2456,2456
AZ,2418,2418,2418,2418,2418,2418,2418,2418,2418,2418,...,2418,2418,2418,2418,2418,2418,2418,2418,2418,2418
GA,2311,2311,2311,2311,2311,2311,2311,2311,2311,2311,...,2311,2311,2311,2311,2311,2311,2311,2311,2311,2311
WI,2258,2258,2258,2258,2258,2258,2258,2258,2258,2258,...,2258,2258,2258,2258,2258,2258,2258,2258,2258,2258
VA,2123,2123,2123,2123,2123,2123,2123,2123,2123,2123,...,2123,2123,2123,2123,2123,2123,2123,2123,2123,2123
CO,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920,...,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920
IN,1912,1912,1912,1912,1912,1912,1912,1912,1912,1912,...,1912,1912,1912,1912,1912,1912,1912,1912,1912,1912
TN,1878,1878,1878,1878,1878,1878,1878,1878,1878,1878,...,1878,1878,1878,1878,1878,1878,1878,1878,1878,1878
MA,1847,1847,1847,1847,1847,1847,1847,1847,1847,1847,...,1847,1847,1847,1847,1847,1847,1847,1847,1847,1847
OK,1794,1794,1794,1794,1794,1794,1794,1794,1794,1794,...,1794,1794,1794,1794,1794,1794,1794,1794,1794,1794
AL,1536,1536,1536,1536,1536,1536,1536,1536,1536,1536,...,1536,1536,1536,1536,1536,1536,1536,1536,1536,1536
KY,1536,1536,1536,1536,1536,1536,1536,1536,1536,1535,...,1536,1536,1536,1536,1536,1536,1536,1536,1536,1536
MD,1420,1420,1420,1420,1420,1420,1420,1420,1420,1420,...,1420,1420,1420,1420,1420,1420,1420,1420,1420,1420
LA,1364,1364,1364,1364,1364,1364,1364,1364,1364,1364,...,1364,1364,1364,1364,1364,1364,1364,1364,1364,1364
KS,1311,1311,1311,1311,1311,1311,1311,1311,1311,1311,...,1311,1311,1311,1311,1311,1311,1311,1311,1311,1311
IA,1310,1310,1310,1310,1310,1310,1310,1310,1310,1310,...,1310,1310,1310,1310,1310,1310,1310,1310,1310,1310
SC,1269,1269,1269,1269,1269,1269,1269,1269,1269,1269,...,1269,1269,1269,1269,1269,1269,1269,1269,1269,1269
OR,1255,1255,1255,1255,1255,1255,1255,1255,1255,1255,...,1255,1255,1255,1255,1255,1255,1255,1255,1255,1255
UT,1087,1087,1087,1087,1087,1087,1087,1087,1087,1087,...,1087,1087,1087,1087,1087,1087,1087,1087,1087,1087
NE,1082,1082,1082,1082,1082,1082,1082,1082,1082,1082,...,1082,1082,1082,1082,1082,1082,1082,1082,1082,1082
AR,1077,1077,1077,1077,1077,1077,1077,1077,1077,1077,...,1077,1077,1077,1077,1077,1077,1077,1077,1077,1077
MS,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,...,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047
CT,1005,1005,1005,1005,1005,1005,1005,1005,1005,1005,...,1005,1005,1005,1005,1005,1005,1005,1005,1005,1005
NM,885,885,885,885,885,885,885,885,885,885,...,885,885,885,885,885,885,885,885,885,885
PR,847,847,847,847,847,847,847,847,847,847,...,847,847,847,847,847,847,847,847,847,847
MT,828,828,828,828,828,828,828,828,828,828,...,828,828,828,828,828,828,828,828,828,828
ID,772,772,772,772,772,772,772,772,772,772,...,772,772,772,772,772,772,772,772,772,772
NV,750,750,750,750,750,750,750,750,750,750,...,750,750,750,750,750,750,750,750,750,750
WV,725,725,725,725,725,725,725,725,725,725,...,725,725,725,725,725,725,725,725,725,725
SD,708,708,708,708,708,708,708,708,708,708,...,708,708,708,708,708,708,708,708,708,708
ME,599,599,599,599,599,599,599,599,599,599,...,599,599,599,599,599,599,599,599,599,599
AK,506,506,506,506,506,506,506,506,506,506,...,506,506,506,506,506,506,506,506,506,506
NH,497,497,497,497,497,497,497,497,497,497,...,497,497,497,497,497,497,497,497,497,497
ND,491,491,491,491,491,491,491,491,491,491,...,491,491,491,491,491,491,491,491,491,491
WY,360,360,360,360,360,360,360,360,360,360,...,360,360,360,360,360,360,360,360,360,360
RI,316,316,316,316,316,316,316,316,316,316,...,316,316,316,316,316,316,316,316,316,316
VT,308,308,308,308,308,308,308,308,308,308,...,308,308,308,308,308,308,308,308,308,308
HI,295,295,295,295,295,295,295,295,295,295,...,295,295,295,295,295,295,295,295,295,295
DC,230,230,230,230,230,230,230,230,230,230,...,230,230,230,230,230,230,230,230,230,230
DE,226,226,226,226,226,226,226,226,226,224,...,226,226,226,226,226,226,226,226,226,226
BI,174,174,174,174,174,174,174,174,174,174,...,174,174,174,174,174,174,174,174,174,174
GU,44,44,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
AS,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,29,29
VI,23,23,23,23,23,23,23,23,23,23,...,23,23,23,23,23,23,23,23,23,23

In [369]:
elem_schools_1920=pubschool1920.loc[pubschool1920['SCHOOL_LEVEL']=='Elementary']

In [377]:
percent_elem_1920=(round(elem_schools_1920.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME/(pubschool1920.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME)*100, 3).reset_index())

In [378]:
percent_elem_1920=percent_elem_1920.rename(columns={'STABR':'State', 'SCH_NAME':'Percent_elem'})

In [382]:
percent_elem_1920

   State  Percent_elem
0     AK        33.992
1     AL        45.443
2     AR        47.911
3     AS        79.310
4     AZ        49.380
5     BI        62.069
6     CA        57.586
7     CO        54.323
8     CT        60.100
9     DC        60.870
10    DE        52.212
11    FL        52.215
12    GA        56.599
13    GU        61.364
14    HI        62.373
15    IA        52.366
16    ID        49.093
17    IL        54.930
18    IN        55.805
19    KS        55.454
20    KY        47.461
21    LA        53.299
22    MA        57.066
23    MD        62.817
24    ME        58.598
25    MI        46.856
26    MN        37.974
27    MO        49.837
28    MS        42.598
29    MT        51.691
30    NC        54.549
31    ND        55.397
32    NE        49.908
33    NH        57.344
34    NJ        58.963
35    NM        51.412
36    NV        56.533
37    NY        53.176
38    OH        50.551
39    OK        52.230
40    OR        56.574
41    PA        55.574
42    PR        60.921
43    RI        55.380
44    SC        54.610
45    SD        46.186
46    TN        53.940
47    TX        49.358
48    UT        57.222
49    VA        53.886
50    VI        65.217
51    VT        68.182
52    WA        48.808
53    WI        50.399
54    WV        58.345
55    WY        54.444

In [379]:
mid_schools_1920=pubschool1920.loc[pubschool1920['SCHOOL_LEVEL']=='Middle']

In [380]:
percent_mid_1920=(round(mid_schools_1920.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME/(pubschool1920.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME)*100, 3).reset_index())

In [391]:
percent_mid_1920=percent_mid_1920.rename(columns={'STABR':'State','SCH_NAME':'Percent_mid'})

In [392]:
percent_mid_1920

   State  Percent_mid
0     AK        7.312
1     AL       16.602
2     AR       19.591
3     AS          NaN
4     AZ        9.553
5     BI        2.874
6     CA       13.631
7     CO       15.104
8     CT       18.109
9     DC       16.957
10    DE       16.814
11    FL       14.020
12    GA       20.727
13    GU       20.455
14    HI       13.898
15    IA       19.389
16    ID       14.508
17    IL       16.870
18    IN       17.626
19    KS       16.934
20    KY       14.388
21    LA       16.789
22    MA       17.325
23    MD       16.056
24    ME       14.691
25    MI       14.486
26    MN       12.142
27    MO       16.164
28    MS       17.861
29    MT       27.295
30    NC       18.121
31    ND        8.350
32    NE       11.645
33    NH       20.523
34    NJ       16.875
35    NM       18.644
36    NV       15.200
37    NY       16.677
38    OH       18.536
39    OK       20.178
40    OR       16.255
41    PA       17.838
42    PR       11.216
43    RI       18.354
44    SC       19.937
45    SD       23.729
46    TN       18.317
47    TX       18.525
48    UT       13.155
49    VA       16.533
50    VI       13.043
51    VT        8.117
52    WA       15.273
53    WI       18.158
54    WV       15.310
55    WY       16.944

In [387]:
hi_schools_1920=pubschool1920.loc[pubschool1920['SCHOOL_LEVEL']=='High']

In [389]:
percent_hi_1920=(round(hi_schools_1920.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME/(pubschool1920.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME)*100, 3).reset_index())

In [395]:
percent_hi_1920=percent_hi_1920.rename(columns={'STABR':'State', 'SCH_NAME':'Percent_high'})

In [396]:
percent_hi_1920

   State  Percent_high
0     AK        15.613
1     AL        26.693
2     AR        28.227
3     AS        20.690
4     AZ        31.307
5     BI        12.644
6     CA        21.674
7     CO        22.552
8     CT        19.602
9     DC        17.826
10    DE        18.584
11    FL        22.620
12    GA        19.602
13    GU        15.909
14    HI        13.898
15    IA        25.802
16    ID        26.166
17    IL        21.903
18    IN        21.287
19    KS        26.163
20    KY        23.828
21    LA        20.381
22    MA        20.141
23    MD        17.254
24    ME        19.533
25    MI        28.411
26    MN        36.118
27    MO        26.873
28    MS        30.277
29    MT        20.773
30    NC        21.302
31    ND        33.401
32    NE        24.861
33    NH        19.517
34    NJ        18.940
35    NM        24.294
36    NV        18.933
37    NY        24.581
38    OH        25.431
39    OK        26.143
40    OR        21.355
41    PA        24.223
42    PR        22.904
43    RI        21.203
44    SC        22.695
45    SD        27.119
46    TN        20.980
47    TX        19.958
48    UT        18.399
49    VA        15.261
50    VI        17.391
51    VT        21.104
52    WA        26.303
53    WI        25.066
54    WV        20.138
55    WY        24.167

In [393]:
schools1920=percent_elem_1920.merge(percent_mid_1920, how='inner', on='State')

In [397]:
schools1920=schools1920.merge(percent_hi_1920, how='inner', on='State')

In [399]:
schools1920['Percent_unaccounted']=(100-(schools1920.Percent_elem+schools1920.Percent_high+schools1920.Percent_mid))

In [400]:
schools1920

   State  Percent_elem  Percent_mid  Percent_high  Percent_unaccounted
0     AK        33.992        7.312        15.613               43.083
1     AL        45.443       16.602        26.693               11.262
2     AR        47.911       19.591        28.227                4.271
3     AS        79.310          NaN        20.690                  NaN
4     AZ        49.380        9.553        31.307                9.760
5     BI        62.069        2.874        12.644               22.413
6     CA        57.586       13.631        21.674                7.109
7     CO        54.323       15.104        22.552                8.021
8     CT        60.100       18.109        19.602                2.189
9     DC        60.870       16.957        17.826                4.347
10    DE        52.212       16.814        18.584               12.390
11    FL        52.215       14.020        22.620               11.145
12    GA        56.599       20.727        19.602                3.072
13    GU        61.364       20.455        15.909                2.272
14    HI        62.373       13.898        13.898                9.831
15    IA        52.366       19.389        25.802                2.443
16    ID        49.093       14.508        26.166               10.233
17    IL        54.930       16.870        21.903                6.297
18    IN        55.805       17.626        21.287                5.282
19    KS        55.454       16.934        26.163                1.449
20    KY        47.461       14.388        23.828               14.323
21    LA        53.299       16.789        20.381                9.531
22    MA        57.066       17.325        20.141                5.468
23    MD        62.817       16.056        17.254                3.873
24    ME        58.598       14.691        19.533                7.178
25    MI        46.856       14.486        28.411               10.247
26    MN        37.974       12.142        36.118               13.766
27    MO        49.837       16.164        26.873                7.126
28    MS        42.598       17.861        30.277                9.264
29    MT        51.691       27.295        20.773                0.241
30    NC        54.549       18.121        21.302                6.028
31    ND        55.397        8.350        33.401                2.852
32    NE        49.908       11.645        24.861               13.586
33    NH        57.344       20.523        19.517                2.616
34    NJ        58.963       16.875        18.940                5.222
35    NM        51.412       18.644        24.294                5.650
36    NV        56.533       15.200        18.933                9.334
37    NY        53.176       16.677        24.581                5.566
38    OH        50.551       18.536        25.431                5.482
39    OK        52.230       20.178        26.143                1.449
40    OR        56.574       16.255        21.355                5.816
41    PA        55.574       17.838        24.223                2.365
42    PR        60.921       11.216        22.904                4.959
43    RI        55.380       18.354        21.203                5.063
44    SC        54.610       19.937        22.695                2.758
45    SD        46.186       23.729        27.119                2.966
46    TN        53.940       18.317        20.980                6.763
47    TX        49.358       18.525        19.958               12.159
48    UT        57.222       13.155        18.399               11.224
49    VA        53.886       16.533        15.261               14.320
50    VI        65.217       13.043        17.391                4.349
51    VT        68.182        8.117        21.104                2.597
52    WA        48.808       15.273        26.303                9.616
53    WI        50.399       18.158        25.066                6.377
54    WV        58.345       15.310        20.138                6.207
55    WY        54.444       16.944        24.167                4.445

In [437]:
tn_scores=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/data/TN_SCORES.csv')

In [438]:
tn_scores

,district_number,district_name,subgroup,valid_tests,participation_rate,average_english_score,average_math_score,average_reading_score,average_science_score,average_composite_score,number_scoring_21_or_higher,percent_scoring_21_or_higher,number_scoring_below_19,percent_scoring_below_19
0,10,Anderson County,All Students,527,100,19,18.7,19.90,19.60,19.5,198,37.6,254,48.2
1,10,Anderson County,Black/Hispanic/Native American,17,100,18,17.8,17.5,18.3,17.9,5,29.4,10,58.8
2,10,Anderson County,Economically Disadvantaged,189,99,17.10,17.2,18.6,18.10,17.9,43,22.8,118,62.4
3,10,Anderson County,English Learners,3,*,*,*,*,*,*,*,*,*,*
4,10,Anderson County,Students with Disabilities,76,100,12.5,15.5,14.5,15.1,14.6,2,2.6,71,93.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,985,Achievement School District,All Students,294,83,13.4,15.4,14.8,15,14.8,14,4.8,261,88.8
591,985,Achievement School District,Black/Hispanic/Native American,292,83,13.4,15.4,14.9,15,14.8,14,4.8,259,88.7
592,985,Achievement School District,Economically Disadvantaged,244,83,13.2,15.2,14.6,14.7,14.6,9,3.7,221,90.6
593,985,Achievement School District,English Learners,7,*,*,*,*,*,*,*,*,*,*
594,985,Achievement School District,Students with Disabilities,40,67,11,14.6,13,13.1,13,**,**,**,**

In [439]:
places_data=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/data/places_data.csv')

In [440]:
places_data

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Latitude,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocatioin
0,2018,US,United States,NaN,BRFSS,Prevention,Current lack of health insurance among adults ...,%,Crude prevalence,12.2,...,NaN,11.9,12.4,327167434,NaN,PREVENT,ACCESS2,CrdPrv,Health Insurance,NaN
1,2018,US,United States,NaN,BRFSS,Prevention,Current lack of health insurance among adults ...,%,Age-adjusted prevalence,13.1,...,NaN,12.9,13.4,327167434,NaN,PREVENT,ACCESS2,AgeAdjPrv,Health Insurance,NaN
2,2018,US,United States,NaN,BRFSS,Health Outcomes,Arthritis among adults aged >=18 years,%,Crude prevalence,25.8,...,NaN,25.6,26.1,327167434,NaN,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,NaN
3,2018,US,United States,NaN,BRFSS,Health Outcomes,Arthritis among adults aged >=18 years,%,Age-adjusted prevalence,23.1,...,NaN,22.9,23.3,327167434,NaN,HLTHOUT,ARTHRITIS,AgeAdjPrv,Arthritis,NaN
4,2018,US,United States,NaN,BRFSS,Unhealthy Behaviors,Binge drinking among adults aged >=18 years,%,Crude prevalence,16.4,...,NaN,16.2,16.7,327167434,NaN,UNHBEH,BINGE,CrdPrv,Binge Drinking,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176003,2018,WY,Wyoming,Weston,BRFSS,Unhealthy Behaviors,Sleeping less than 7 hours among adults aged >...,%,Age-adjusted prevalence,34.5,...,NaN,32.8,36.1,6967,43.840312,UNHBEH,SLEEP,AgeAdjPrv,Sleep <7 hours,POINT (-104.567594 43.84031158)
176004,2018,WY,Wyoming,Weston,BRFSS,Health Outcomes,Stroke among adults aged >=18 years,%,Crude prevalence,4.0,...,NaN,3.6,4.5,6967,43.840312,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-104.567594 43.84031158)
176005,2018,WY,Wyoming,Weston,BRFSS,Health Outcomes,Stroke among adults aged >=18 years,%,Age-adjusted prevalence,3.1,...,NaN,2.8,3.4,6967,43.840312,HLTHOUT,STROKE,AgeAdjPrv,Stroke,POINT (-104.567594 43.84031158)
176006,2018,WY,Wyoming,Weston,BRFSS,Health Outcomes,All teeth lost among adults aged >=65 years,%,Crude prevalence,17.7,...,NaN,11.8,24.3,6967,43.840312,HLTHOUT,TEETHLOST,CrdPrv,Teeth Loss,POINT (-104.567594 43.84031158)
176007,2018,WY,Wyoming,Weston,BRFSS,Health Outcomes,All teeth lost among adults aged >=65 years,%,Age-adjusted prevalence,18.0,...,NaN,11.9,24.6,6967,43.840312,HLTHOUT,TEETHLOST,AgeAdjPrv,Teeth Loss,POINT (-104.567594 43.84031158)

In [ ]:
prev_data=places_data.loc[places_data['Category']=='Prevention']

In [ ]:
prev_data.loc[prev_data['StateDesc']=='Tennessee']

In [ ]:
prev_data.loc[prev_data['StateDesc']=='Tennessee'].Measure.unique()

In [ ]:
uninsured=prev_data.loc[(prev_data['Measure']=='Current lack of health insurance among adults aged 18-64 years')&(prev_data['Data_Value_Type']=='Crude prevalence')]

In [ ]:
avg_uninsured_percent=pd.DataFrame()

In [ ]:
for i in state_list:
    avg_uninsured_percent=avg_uninsured_percent.append(uninsured.loc[(uninsured['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())

In [ ]:
avg_uninsured_percent=avg_uninsured_percent.sort_values('StateAbbr')

In [ ]:
avg_uninsured_percent=avg_uninsured_percent.reset_index().rename(columns={'StateAbbr':'State', 'Data_Value':'Percent_uninsured'})

In [ ]:
avg_uninsured_percent

In [ ]:
health_data=places_data.loc[places_data['Category']=='Health Outcomes']

In [ ]:
health_data.Measure.unique()

In [ ]:
health_data

In [ ]:
stroke_data=health_data.loc[health_data['Measure']=='Stroke among adults aged >=18 years']

In [ ]:
stroke_data.loc[(stroke_data['StateDesc']=='Kansas')&(stroke_data['Data_Value_Type']=='Crude prevalence'), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean()

In [ ]:
state_list=stroke_data.StateDesc.unique().tolist()

In [ ]:
avg_stroke_percent=pd.DataFrame()

In [ ]:
for i in state_list:
    avg_stroke_percent=avg_stroke_percent.append(stroke_data.loc[(stroke_data['StateDesc']==i)&(stroke_data['Data_Value_Type']=='Crude prevalence'), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())

In [ ]:
avg_stroke_percent=avg_stroke_percent.sort_values('StateAbbr')

In [ ]:
avg_stroke_percent=avg_stroke_percent.reset_index().rename(columns={'StateAbbr':'State', 'Data_Value':'Percent_stroke'})

In [ ]:
avg_stroke_percent

In [ ]:
diabetes_data=health_data.loc[health_data['Measure']=='Diagnosed diabetes among adults aged >=18 years']

In [ ]:
diabetes_data

In [ ]:
avg_diabetes_percent=pd.DataFrame()

In [ ]:
for i in state_list:
    avg_diabetes_percent=avg_diabetes_percent.append(diabetes_data.loc[(diabetes_data['StateDesc']==i)&(diabetes_data['Data_Value_Type']=='Crude prevalence'), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())

In [ ]:
avg_diabetes_percent=avg_diabetes_percent.sort_values('StateAbbr')

In [ ]:
avg_diabetes_percent=avg_diabetes_percent.reset_index().rename(columns={'StateAbbr':'State', 'Data_Value':'Percent_Diabetes'})

In [ ]:
avg_diabetes_percent

In [ ]:
'Coronary heart disease among adults aged >=18 years'

In [ ]:
heart_data=health_data.loc[health_data['Measure']=='Coronary heart disease among adults aged >=18 years']

In [ ]:
heart_data

In [ ]:
avg_heart_percent=pd.DataFrame()

In [ ]:
for i in state_list:
    avg_heart_percent=avg_heart_percent.append(heart_data.loc[(heart_data['StateDesc']==i)&(heart_data['Data_Value_Type']=='Crude prevalence'), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())

In [ ]:
avg_heart_percent=avg_heart_percent.sort_values('StateAbbr')

In [ ]:
avg_heart_percent=avg_heart_percent.reset_index().rename(columns={'StateAbbr':'State', 'Data_Value':'Percent_heart'})

In [ ]:
avg_heart_percent

In [ ]:
mid_health=avg_stroke_percent.merge(avg_diabetes_percent, how='inner', on='State')

In [ ]:
health_metrics=mid_health.merge(avg_heart_percent, how='inner', on='State')

In [ ]:
health_metrics=health_metrics.merge(avg_uninsured_percent, how='inner', on='State')

In [ ]:
health_metrics

In [412]:
big_df=health_metrics.merge(schools1920, how='inner', on='State')

In [402]:
big_df

,State,Percent_stroke,Percent_Diabetes,Percent_heart,Percent_uninsured,Percent_elem,Percent_mid,Percent_high,Percent_unaccounted
0,AK,3.879310,11.934483,7.372414,14.155172,33.992,7.312,15.613,43.083
1,AL,4.967164,16.235821,9.626866,16.647761,45.443,16.602,26.693,11.262
2,AR,4.802667,14.881333,10.233333,14.853333,47.911,19.591,28.227,4.271
3,AZ,4.520000,13.033333,9.000000,16.680000,49.380,9.553,31.307,9.760
4,CA,3.543103,11.322414,6.906897,13.824138,57.586,13.631,21.674,7.109
5,CO,3.445312,9.771875,6.981250,14.493750,54.323,15.104,22.552,8.021
6,CT,3.012500,9.587500,6.312500,9.000000,60.100,18.109,19.602,2.189
7,DC,3.000000,8.100000,4.100000,8.500000,60.870,16.957,17.826,4.347
8,DE,3.966667,12.900000,7.700000,14.466667,52.212,16.814,18.584,12.390
9,FL,4.501493,13.897015,9.592537,23.131343,52.215,14.020,22.620,11.145
10,GA,4.642767,15.083648,8.623899,23.747799,56.599,20.727,19.602,3.072
11,HI,4.240000,12.240000,7.680000,10.840000,62.373,13.898,13.898,9.831
12,IA,3.667677,10.981818,7.882828,10.318182,52.366,19.389,25.802,2.443
13,ID,3.936364,12.318182,8.172727,17.870455,49.093,14.508,26.166,10.233
14,IL,3.870588,11.446078,8.044118,12.984314,54.930,16.870,21.903,6.297
15,IN,3.810870,12.903261,8.090217,13.575000,55.805,17.626,21.287,5.282
16,KS,3.863810,12.735238,8.313333,16.076190,55.454,16.934,26.163,1.449
17,KY,4.470000,15.424167,10.521667,10.916667,47.461,14.388,23.828,14.323
18,LA,4.831250,15.101562,9.093750,15.228125,53.299,16.789,20.381,9.531
19,MA,3.064286,9.292857,6.528571,8.550000,57.066,17.325,20.141,5.468
20,MD,3.620833,12.283333,7.029167,9.837500,62.817,16.056,17.254,3.873
21,ME,3.962500,11.537500,8.743750,14.031250,58.598,14.691,19.533,7.178
22,MI,4.103614,12.531325,9.371084,9.939759,46.856,14.486,28.411,10.247
23,MN,3.583908,10.454023,7.393103,10.681609,37.974,12.142,36.118,13.766
24,MO,4.352174,12.952174,9.107826,16.144348,49.837,16.164,26.873,7.126
25,MS,5.167073,16.304878,9.296341,20.975610,42.598,17.861,30.277,9.264
26,MT,4.214286,11.889286,8.539286,12.875000,51.691,27.295,20.773,0.241
27,NC,4.557000,14.176000,9.058000,18.949000,54.549,18.121,21.302,6.028
28,ND,3.873585,11.837736,8.601887,11.160377,55.397,8.350,33.401,2.852
29,NE,3.852688,11.397849,8.134409,12.668817,49.908,11.645,24.861,13.586
30,NH,3.250000,10.750000,7.230000,10.330000,57.344,20.523,19.517,2.616
31,NJ,3.228571,11.052381,6.619048,13.457143,58.963,16.875,18.940,5.222
32,NM,4.324242,14.442424,8.669697,15.087879,51.412,18.644,24.294,5.650
33,NV,3.994118,12.464706,8.811765,14.517647,56.533,15.200,18.933,9.334
34,NY,3.498387,11.514516,7.656452,12.006452,53.176,16.677,24.581,5.566
35,OH,3.903409,12.853409,8.628409,9.845455,50.551,18.536,25.431,5.482
36,OK,4.423377,13.836364,9.619481,18.009091,52.230,20.178,26.143,1.449
37,OR,4.105556,12.552778,8.697222,13.411111,56.574,16.255,21.355,5.816
38,PA,3.817910,11.900000,8.031343,10.086567,55.574,17.838,24.223,2.365
39,RI,3.200000,10.100000,6.820000,8.540000,55.380,18.354,21.203,5.063
40,SC,4.754348,15.441304,8.573913,19.019565,54.610,19.937,22.695,2.758
41,SD,4.168182,11.836364,8.680303,13.057576,46.186,23.729,27.119,2.966
42,TN,4.469474,14.532632,9.731579,16.448421,53.940,18.317,20.980,6.763
43,TX,4.073228,14.411024,8.796457,28.470866,49.358,18.525,19.958,12.159
44,UT,3.265517,10.320690,6.410345,14.813793,57.222,13.155,18.399,11.224
45,VA,4.088722,12.845113,8.139098,16.072932,53.886,16.533,15.261,14.320
46,VT,3.485714,10.021429,7.071429,9.742857,68.182,8.117,21.104,2.597
47,WA,3.810256,11.520513,7.869231,12.028205,48.808,15.273,26.303,9.616
48,WI,3.702778,10.597222,7.791667,11.347222,50.399,18.158,25.066,6.377
49,WV,4.530909,15.836364,11.183636,11.958182,58.345,15.310,20.138,6.207
50,WY,3.513043,10.204348,7.326087,15.586957,54.444,16.944,24.167,4.445

In [ ]:
math_2022_4=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/Math_2022_4.csv')

In [ ]:
math_2022_4

In [ ]:
math_2022_4=math_2022_4.rename(columns={'Jurisdiction':'State', 'MN':'avg_score', 'SigDiff':'diff', 'AB':'above_basic','AP':'above_proficient'})

In [ ]:
math_2019_4=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/Math_2019_4.csv')

In [ ]:
math_2019_4=math_2019_4.rename(columns={'Jurisdiction':'State', 'MN':'avg_score_math', 'SigDiff':'diff_math', 'AB':'math_AB','AP':'math_AP'})

In [ ]:
math_2019_4=math_2019_4.drop(columns=['SigSymbol'])

In [ ]:
math_2019_4

In [ ]:
reading_19_4=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/Reading_2019_4.csv')

In [ ]:
reading_19_4=reading_19_4.rename(columns={'jurisdiction':'State', 'avg_score':'avg_score_read', 'Diff_NP':'diff_read', 'At_or_above_B':'read_AB','At_or_above_P':'read_AP'})

In [ ]:
reading_19_4=reading_19_4.drop(columns=['SigSymbol'])

In [ ]:
reading_19_4

In [ ]:
scores_2019=reading_19_4.merge(math_2019_4, how='inner', on='State')

In [ ]:
scores_2019

In [ ]:
reading_19_8=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/Reading_2019_8.csv')

In [ ]:
reading_19_8=reading_19_8.drop(columns=['SigSymbol'])

In [ ]:
math_19_8=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/Math_2019_8.csv')

In [ ]:
math_19_8=math_19_8.drop(columns=['SigSymbol'])

In [ ]:
math_19_8

In [414]:
big_df=big_df.merge(scores_2019, how='inner', on='State')

In [421]:
big_df=big_df.merge(ado_mmr_2018_f, how='inner', on='State')

In [422]:
big_df=big_df.merge(pne_vax_2018_f, how='inner', on='State')

In [423]:
big_df=big_df.merge(hpv_vax_2018_f, how='inner', on='State')

In [416]:
big_df=big_df.rename(columns={'avg_score_read':'avg_score_read_4th', 'diff_read':'diff_read_4th', 'read_AB':'read_AB_4th', 'read_AP':'read_AP_4th', 'avg_score_math':'avg_score_math_4th', 'diff_math':'diff_math_4th', 'math_AB':'math_AB_4th', 'math_AP':'math_AP_4th'})

In [418]:
big_df=big_df.merge(reading_19_8, how='inner', on='State')

In [419]:
big_df=big_df.merge(math_19_8, how='inner', on='State')

In [424]:
big_df=big_df.merge(hepb_vax_2018_f, how='inner', on='State')

In [425]:
big_df

,State,Percent_stroke,Percent_Diabetes,Percent_heart,Percent_uninsured,Percent_elem,Percent_mid,Percent_high,Percent_unaccounted,avg_score_read_4th,...,read_AB_8th,read_AP_8th,avg_math_score_8th,diff_math_8th,math_AB_8th,math_AP_8th,Percentage_MMR,Percentage_Pneumococcal,Percentage_HPV,Percentage_HepB
0,AK,3.879310,11.934483,7.372414,14.155172,33.992,7.312,15.613,43.083,204,...,63,23,274,-7,63,29,91.2,64.2,44.1,89.5
1,AL,4.967164,16.235821,9.626866,16.647761,45.443,16.602,26.693,11.262,212,...,64,24,269,-12,57,21,92.8,71.7,50.2,94.2
2,AR,4.802667,14.881333,10.233333,14.853333,47.911,19.591,28.227,4.271,215,...,68,30,274,-7,63,27,92.0,75.0,42.6,91.4
3,AZ,4.520000,13.033333,9.000000,16.680000,49.380,9.553,31.307,9.760,216,...,70,28,280,-1,68,31,88.3,74.0,50.7,89.1
4,CA,3.543103,11.322414,6.906897,13.824138,57.586,13.631,21.674,7.109,216,...,68,30,276,-5,61,29,91.1,68.9,52.6,88.8
5,CO,3.445312,9.771875,6.981250,14.493750,54.323,15.104,22.552,8.021,225,...,77,38,285,4,73,37,92.7,77.5,62.5,93.5
6,CT,3.012500,9.587500,6.312500,9.000000,60.100,18.109,19.602,2.189,224,...,78,41,286,5,72,39,95.9,72.4,53.1,95.9
7,DC,3.000000,8.100000,4.100000,8.500000,60.870,16.957,17.826,4.347,214,...,58,23,269,-12,55,23,NaN,71.0,71.3,NaN
8,DE,3.966667,12.900000,7.700000,14.466667,52.212,16.814,18.584,12.390,218,...,69,31,277,-4,65,29,95.7,73.0,58.4,94.3
9,FL,4.501493,13.897015,9.592537,23.131343,52.215,14.020,22.620,11.145,225,...,72,34,279,-2,66,31,96.1,67.3,46.5,97.6
10,GA,4.642767,15.083648,8.623899,23.747799,56.599,20.727,19.602,3.072,218,...,72,32,279,-1,67,31,97.0,71.2,49.6,95.4
11,HI,4.240000,12.240000,7.680000,10.840000,62.373,13.898,13.898,9.831,218,...,68,29,275,-6,65,28,93.7,65.3,60.7,93.4
12,IA,3.667677,10.981818,7.882828,10.318182,52.366,19.389,25.802,2.443,221,...,73,33,282,1,72,33,96.0,76.3,55.1,95.5
13,ID,3.936364,12.318182,8.172727,17.870455,49.093,14.508,26.166,10.233,223,...,77,37,286,5,74,37,88.5,70.5,43.4,88.4
14,IL,3.870588,11.446078,8.044118,12.984314,54.930,16.870,21.903,6.297,218,...,74,35,283,2,69,34,94.6,68.6,53.4,94.5
15,IN,3.810870,12.903261,8.090217,13.575000,55.805,17.626,21.287,5.282,222,...,75,37,286,5,73,37,95.9,72.5,48.9,95.9
16,KS,3.863810,12.735238,8.313333,16.076190,55.454,16.934,26.163,1.449,219,...,74,32,282,1,71,33,86.5,76.2,40.7,85.8
17,KY,4.470000,15.424167,10.521667,10.916667,47.461,14.388,23.828,14.323,221,...,73,33,278,-3,67,29,91.7,72.6,42.6,91.9
18,LA,4.831250,15.101562,9.093750,15.228125,53.299,16.789,20.381,9.531,210,...,68,27,272,-9,61,23,94.8,68.6,46.7,93.4
19,MA,3.064286,9.292857,6.528571,8.550000,57.066,17.325,20.141,5.468,231,...,81,45,294,13,78,47,97.9,73.4,68.7,97.9
20,MD,3.620833,12.283333,7.029167,9.837500,62.817,16.056,17.254,3.873,220,...,73,36,280,-1,65,33,94.1,75.7,58.1,93.4
21,ME,3.962500,11.537500,8.743750,14.031250,58.598,14.691,19.533,7.178,221,...,75,36,282,1,71,34,94.6,77.2,50.7,94.5
22,MI,4.103614,12.531325,9.371084,9.939759,46.856,14.486,28.411,10.247,218,...,73,31,280,-1,68,31,91.0,74.2,55.0,91.6
23,MN,3.583908,10.454023,7.393103,10.681609,37.974,12.142,36.118,13.766,222,...,74,34,291,10,77,44,97.1,72.7,58.8,93.8
24,MO,4.352174,12.952174,9.107826,16.144348,49.837,16.164,26.873,7.126,218,...,74,33,281,0,70,32,89.4,74.4,42.1,90.7
25,MS,5.167073,16.304878,9.296341,20.975610,42.598,17.861,30.277,9.264,219,...,67,25,274,-7,62,24,94.2,68.7,32.6,91.9
26,MT,4.214286,11.889286,8.539286,12.875000,51.691,27.295,20.773,0.241,222,...,76,34,284,3,73,36,92.3,73.3,48.4,88.9
27,NC,4.557000,14.176000,9.058000,18.949000,54.549,18.121,21.302,6.028,221,...,72,33,284,3,71,37,92.5,76.7,52.1,93.2
28,ND,3.873585,11.837736,8.601887,11.160377,55.397,8.350,33.401,2.852,221,...,75,32,286,5,75,37,96.4,75.2,63.6,97.5
29,NE,3.852688,11.397849,8.134409,12.668817,49.908,11.645,24.861,13.586,222,...,74,34,285,4,74,37,93.1,76.6,62.7,91.9
30,NH,3.250000,10.750000,7.230000,10.330000,57.344,20.523,19.517,2.616,224,...,78,38,287,6,77,38,98.8,78.6,67.4,97.3
31,NJ,3.228571,11.052381,6.619048,13.457143,58.963,16.875,18.940,5.222,227,...,77,43,292,11,76,44,90.5,68.1,48.5,93.4
32,NM,4.324242,14.442424,8.669697,15.087879,51.412,18.644,24.294,5.650,208,...,61,23,269,-12,56,21,90.4,71.3,57.0,91.4
33,NV,3.994118,12.464706,8.811765,14.517647,56.533,15.200,18.933,9.334,218,...,69,29,274,-7,62,26,89.0,68.5,51.1,88.0
34,NY,3.498387,11.514516,7.656452,12.006452,53.176,16.677,24.581,5.566,220,...,70,32,280,-1,66,34,95.2,64.0,57.3,95.9
35,OH,3.903409,12.853409,8.628409,9.845455,50.551,18.536,25.431,5.482,222,...,75,38,286,5,73,38,89.5,74.3,58.2,94.7
36,OK,4.423377,13.836364,9.619481,18.009091,52.230,20.178,26.143,1.449,216,...,71,26,276,-5,66,26,87.7,75.1,37.9,88.0
37,OR,4.105556,12.552778,8.697222,13.411111,56.574,16.255,21.355,5.816,218,...,73,34,280,-1,67,31,93.2,77.3,58.2,93.5
38,PA,3.817910,11.900000,8.031343,10.086567,55.574,17.838,24.223,2.365,223,...,73,35,285,4,70,39,96.2,75.3,54.1,97.2
39,RI,3.200000,10.100000,6.820000,8.540000,55.380,18.354,21.203,5.063,220,...,71,35,276,-5,64,29,97.8,75.5,78.1,96.9
40,SC,4.754348,15.441304,8.573913,19.019565,54.610,19.937,22.695,2.758,216,...,69,29,276,-5,64,29,92.5,73.6,41.2,93.0
41,SD,4.168182,11.836364,8.680303,13.057576,46.186,23.729,27.119,2.966,222,...,74,32,287,6,76,39,97.2,77.0,49.5,95.0
42,TN,4.469474,14.532632,9.731579,16.448421,53.940,18.317,20.980,6.763,219,...,73,32,280,-1,68,31,93.6,74.5,44.4,95.1
43,TX,4.073228,14.411024,8.796457,28.470866,49.358,18.525,19.958,12.159,216,...,67,25,280,-1,68,30,83.1,71.3,43.5,83.5
44,UT,3.265517,10.320690,6.410345,14.813793,57.222,13.155,18.399,11.224,225,...,77,38,285,4,72,37,89.5,73.7,43.2,90.9
45,VA,4.088722,12.845113,8.139098,16.072932,53.886,16.533,15.261,14.320,224,...,71,33,287,6,75,38,92.3,73.9,54.9,91.7
46,VT,3.485714,10.021429,7.071429,9.742857,68.182,8.117,21.104,2.597,222,...,77,40,287,6,75,38,96.0,74.8,62.0,96.6
47,WA,3.810256,11.520513,7.869231,12.028205,48.808,15.273,26.303,9.616,220,...,74,38,286,5,72,40,88.3,78.0,51.6,90.1
48,WI,3.702778,10.597222,7.791667,11.347222,50.399,18.158,25.066,6.377,220,...,76,39,289,8,76,41,93.9,74.9,55.7,94.3
49,WV,4.530909,15.836364,11.183636,11.958182,58.345,15.310,20.138,6.207,213,...,67,25,272,-9,62,24,86.5,73.0,42.9,88.2
50,WY,3.513043,10.204348,7.326087,15.586957,54.444,16.944,24.167,4.445,227,...,75,34,286,5,76,37,90.0,70.1,42.0,91.1

In [427]:
Df1819=big_df

In [364]:
Df1819=Df1819.drop(columns=['Percent_elem', 'Percent_High', 'Percent_mid', 'Percent_unaccounted'])

In [496]:
Df1819

,State,Percent_stroke,Percent_Diabetes,Percent_heart,Percent_uninsured,Percent_elem,Percent_mid,Percent_high,Percent_unaccounted,avg_score_read_4th,...,read_AB_8th,read_AP_8th,avg_math_score_8th,diff_math_8th,math_AB_8th,math_AP_8th,Percentage_MMR,Percentage_Pneumococcal,Percentage_HPV,Percentage_HepB
0,AK,3.879310,11.934483,7.372414,14.155172,33.992,7.312,15.613,43.083,204,...,63,23,274,-7,63,29,91.2,64.2,44.1,89.5
1,AL,4.967164,16.235821,9.626866,16.647761,45.443,16.602,26.693,11.262,212,...,64,24,269,-12,57,21,92.8,71.7,50.2,94.2
2,AR,4.802667,14.881333,10.233333,14.853333,47.911,19.591,28.227,4.271,215,...,68,30,274,-7,63,27,92.0,75.0,42.6,91.4
3,AZ,4.520000,13.033333,9.000000,16.680000,49.380,9.553,31.307,9.760,216,...,70,28,280,-1,68,31,88.3,74.0,50.7,89.1
4,CA,3.543103,11.322414,6.906897,13.824138,57.586,13.631,21.674,7.109,216,...,68,30,276,-5,61,29,91.1,68.9,52.6,88.8
5,CO,3.445312,9.771875,6.981250,14.493750,54.323,15.104,22.552,8.021,225,...,77,38,285,4,73,37,92.7,77.5,62.5,93.5
6,CT,3.012500,9.587500,6.312500,9.000000,60.100,18.109,19.602,2.189,224,...,78,41,286,5,72,39,95.9,72.4,53.1,95.9
7,DC,3.000000,8.100000,4.100000,8.500000,60.870,16.957,17.826,4.347,214,...,58,23,269,-12,55,23,NaN,71.0,71.3,NaN
8,DE,3.966667,12.900000,7.700000,14.466667,52.212,16.814,18.584,12.390,218,...,69,31,277,-4,65,29,95.7,73.0,58.4,94.3
9,FL,4.501493,13.897015,9.592537,23.131343,52.215,14.020,22.620,11.145,225,...,72,34,279,-2,66,31,96.1,67.3,46.5,97.6
10,GA,4.642767,15.083648,8.623899,23.747799,56.599,20.727,19.602,3.072,218,...,72,32,279,-1,67,31,97.0,71.2,49.6,95.4
11,HI,4.240000,12.240000,7.680000,10.840000,62.373,13.898,13.898,9.831,218,...,68,29,275,-6,65,28,93.7,65.3,60.7,93.4
12,IA,3.667677,10.981818,7.882828,10.318182,52.366,19.389,25.802,2.443,221,...,73,33,282,1,72,33,96.0,76.3,55.1,95.5
13,ID,3.936364,12.318182,8.172727,17.870455,49.093,14.508,26.166,10.233,223,...,77,37,286,5,74,37,88.5,70.5,43.4,88.4
14,IL,3.870588,11.446078,8.044118,12.984314,54.930,16.870,21.903,6.297,218,...,74,35,283,2,69,34,94.6,68.6,53.4,94.5
15,IN,3.810870,12.903261,8.090217,13.575000,55.805,17.626,21.287,5.282,222,...,75,37,286,5,73,37,95.9,72.5,48.9,95.9
16,KS,3.863810,12.735238,8.313333,16.076190,55.454,16.934,26.163,1.449,219,...,74,32,282,1,71,33,86.5,76.2,40.7,85.8
17,KY,4.470000,15.424167,10.521667,10.916667,47.461,14.388,23.828,14.323,221,...,73,33,278,-3,67,29,91.7,72.6,42.6,91.9
18,LA,4.831250,15.101562,9.093750,15.228125,53.299,16.789,20.381,9.531,210,...,68,27,272,-9,61,23,94.8,68.6,46.7,93.4
19,MA,3.064286,9.292857,6.528571,8.550000,57.066,17.325,20.141,5.468,231,...,81,45,294,13,78,47,97.9,73.4,68.7,97.9
20,MD,3.620833,12.283333,7.029167,9.837500,62.817,16.056,17.254,3.873,220,...,73,36,280,-1,65,33,94.1,75.7,58.1,93.4
21,ME,3.962500,11.537500,8.743750,14.031250,58.598,14.691,19.533,7.178,221,...,75,36,282,1,71,34,94.6,77.2,50.7,94.5
22,MI,4.103614,12.531325,9.371084,9.939759,46.856,14.486,28.411,10.247,218,...,73,31,280,-1,68,31,91.0,74.2,55.0,91.6
23,MN,3.583908,10.454023,7.393103,10.681609,37.974,12.142,36.118,13.766,222,...,74,34,291,10,77,44,97.1,72.7,58.8,93.8
24,MO,4.352174,12.952174,9.107826,16.144348,49.837,16.164,26.873,7.126,218,...,74,33,281,0,70,32,89.4,74.4,42.1,90.7
25,MS,5.167073,16.304878,9.296341,20.975610,42.598,17.861,30.277,9.264,219,...,67,25,274,-7,62,24,94.2,68.7,32.6,91.9
26,MT,4.214286,11.889286,8.539286,12.875000,51.691,27.295,20.773,0.241,222,...,76,34,284,3,73,36,92.3,73.3,48.4,88.9
27,NC,4.557000,14.176000,9.058000,18.949000,54.549,18.121,21.302,6.028,221,...,72,33,284,3,71,37,92.5,76.7,52.1,93.2
28,ND,3.873585,11.837736,8.601887,11.160377,55.397,8.350,33.401,2.852,221,...,75,32,286,5,75,37,96.4,75.2,63.6,97.5
29,NE,3.852688,11.397849,8.134409,12.668817,49.908,11.645,24.861,13.586,222,...,74,34,285,4,74,37,93.1,76.6,62.7,91.9
30,NH,3.250000,10.750000,7.230000,10.330000,57.344,20.523,19.517,2.616,224,...,78,38,287,6,77,38,98.8,78.6,67.4,97.3
31,NJ,3.228571,11.052381,6.619048,13.457143,58.963,16.875,18.940,5.222,227,...,77,43,292,11,76,44,90.5,68.1,48.5,93.4
32,NM,4.324242,14.442424,8.669697,15.087879,51.412,18.644,24.294,5.650,208,...,61,23,269,-12,56,21,90.4,71.3,57.0,91.4
33,NV,3.994118,12.464706,8.811765,14.517647,56.533,15.200,18.933,9.334,218,...,69,29,274,-7,62,26,89.0,68.5,51.1,88.0
34,NY,3.498387,11.514516,7.656452,12.006452,53.176,16.677,24.581,5.566,220,...,70,32,280,-1,66,34,95.2,64.0,57.3,95.9
35,OH,3.903409,12.853409,8.628409,9.845455,50.551,18.536,25.431,5.482,222,...,75,38,286,5,73,38,89.5,74.3,58.2,94.7
36,OK,4.423377,13.836364,9.619481,18.009091,52.230,20.178,26.143,1.449,216,...,71,26,276,-5,66,26,87.7,75.1,37.9,88.0
37,OR,4.105556,12.552778,8.697222,13.411111,56.574,16.255,21.355,5.816,218,...,73,34,280,-1,67,31,93.2,77.3,58.2,93.5
38,PA,3.817910,11.900000,8.031343,10.086567,55.574,17.838,24.223,2.365,223,...,73,35,285,4,70,39,96.2,75.3,54.1,97.2
39,RI,3.200000,10.100000,6.820000,8.540000,55.380,18.354,21.203,5.063,220,...,71,35,276,-5,64,29,97.8,75.5,78.1,96.9
40,SC,4.754348,15.441304,8.573913,19.019565,54.610,19.937,22.695,2.758,216,...,69,29,276,-5,64,29,92.5,73.6,41.2,93.0
41,SD,4.168182,11.836364,8.680303,13.057576,46.186,23.729,27.119,2.966,222,...,74,32,287,6,76,39,97.2,77.0,49.5,95.0
42,TN,4.469474,14.532632,9.731579,16.448421,53.940,18.317,20.980,6.763,219,...,73,32,280,-1,68,31,93.6,74.5,44.4,95.1
43,TX,4.073228,14.411024,8.796457,28.470866,49.358,18.525,19.958,12.159,216,...,67,25,280,-1,68,30,83.1,71.3,43.5,83.5
44,UT,3.265517,10.320690,6.410345,14.813793,57.222,13.155,18.399,11.224,225,...,77,38,285,4,72,37,89.5,73.7,43.2,90.9
45,VA,4.088722,12.845113,8.139098,16.072932,53.886,16.533,15.261,14.320,224,...,71,33,287,6,75,38,92.3,73.9,54.9,91.7
46,VT,3.485714,10.021429,7.071429,9.742857,68.182,8.117,21.104,2.597,222,...,77,40,287,6,75,38,96.0,74.8,62.0,96.6
47,WA,3.810256,11.520513,7.869231,12.028205,48.808,15.273,26.303,9.616,220,...,74,38,286,5,72,40,88.3,78.0,51.6,90.1
48,WI,3.702778,10.597222,7.791667,11.347222,50.399,18.158,25.066,6.377,220,...,76,39,289,8,76,41,93.9,74.9,55.7,94.3
49,WV,4.530909,15.836364,11.183636,11.958182,58.345,15.310,20.138,6.207,213,...,67,25,272,-9,62,24,86.5,73.0,42.9,88.2
50,WY,3.513043,10.204348,7.326087,15.586957,54.444,16.944,24.167,4.445,227,...,75,34,286,5,76,37,90.0,70.1,42.0,91.1

In [429]:
Df1819.to_csv('HealthSchool_data_1819.csv')

In [441]:
places_2023=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/data/places_2023.csv')

array(['All teeth lost among adults aged >=65 years'], dtype=object)

In [442]:
stroke_2021=places_2023.loc[(places_2023['Year']==2021)&(places_2023['Measure']=='Stroke among adults aged >=18 years')&(places_2023['Data_Value_Type']=='Crude prevalence')]

In [443]:
stroke2021_percent=pd.DataFrame()

In [444]:
for i in state_list:
    stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())

C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2700322976.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stroke2021_percent=stroke2021_percent.append(stroke_2021.loc[(stroke_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())

In [448]:
stroke2021_percent

   State  Percent_stroke
0     AK        3.833898
1     AL        4.043328
2     AR        4.077715
3     AZ        4.352857
4     CA        3.144973
5     CO        2.847917
6     CT        2.809155
7     DC        2.900000
8     DE        3.266234
9     GA        3.912681
10    HI        2.991946
11    IA        3.264823
12    ID        3.335648
13    IL        3.144723
14    IN        3.256509
15    KS        3.412361
16    KY        3.642644
17    LA        4.076110
18    MA        2.805738
19    MD        3.039922
20    ME        3.353846
21    MI        3.396377
22    MN        3.151598
23    MO        3.623108
24    MS        4.387017
25    MT        3.582319
26    NC        3.958470
27    ND        3.516719
28    NE        3.392015
29    NH        2.881443
30    NJ        2.848614
31    NM        3.910766
32    NV        3.563415
33    NY        2.892107
34    OH        3.338829
35    OK        3.916549
36    OR        3.505707
37    PA        3.306910
38    RI        2.897222
39    SC        3.981519
40    SD        3.630149
41    TN        3.756876
42    TX        3.478872
43    UT        2.766144
44    VA        3.423103
45    VT        3.057025
46    WA        3.125163
47    WI        3.130670
48    WV        4.037065
49    WY        3.017582

In [446]:
stroke2021_percent=stroke2021_percent.sort_values('StateAbbr')

In [447]:
stroke2021_percent=stroke2021_percent.reset_index().rename(columns={'StateAbbr':'State', 'Data_Value':'Percent_stroke'})

In [449]:
places_2023.Measure.unique()

array(['All teeth lost among adults aged >=65 years',
       'Arthritis among adults aged >=18 years',
       'Obesity among adults aged >=18 years',
       'Any disability among adults aged >=18 years',
       'Current asthma among adults aged >=18 years',
       'Stroke among adults aged >=18 years',
       'High blood pressure among adults aged >=18 years',
       'Mammography use among women aged 50-74 years',
       'Depression among adults aged >=18 years',
       'Vision disability among adults aged >=18 years',
       'Diagnosed diabetes among adults aged >=18 years',
       'Binge drinking among adults aged >=18 years',
       'Mobility disability among adults aged >=18 years',
       'Hearing disability among adults aged >=18 years',
       'Taking medicine for high blood pressure control among adults aged >=18 years with high blood pressure',
       'Coronary heart disease among adults aged >=18 years',
       'Cognitive disability among adults ages >=18 years',
       'No leisure-time physical activity among adults aged >=18 years',
       'Older adult men aged >=65 years who are up to date on a core set of clinical preventive services: Flu shot past year, PPV shot ever, Colorectal cancer screening',
       'Visits to doctor for routine checkup within the past year among adults aged >=18 years',
       'Cancer (excluding skin cancer) among adults aged >=18 years',
       'Mental health not good for >=14 days among adults aged >=18 years',
       'Independent living disability among adults aged >=18 years',
       'Visits to dentist or dental clinic among adults aged >=18 years',
       'Chronic obstructive pulmonary disease among adults aged >=18 years',
       'Self-care disability among adults aged >=18 years',
       'Current smoking among adults aged >=18 years',
       'Physical health not good for >=14 days among adults aged >=18 years',
       'Current lack of health insurance among adults aged 18-64 years',
       'Sleeping less than 7 hours among adults aged >=18 years',
       'High cholesterol among adults aged >=18 years who have been screened in the past 5 years',
       'Cholesterol screening among adults aged >=18 years',
       'Fecal occult blood test, sigmoidoscopy, or colonoscopy among adults aged 50-75 years',
       'Chronic kidney disease among adults aged >=18 years',
       'Cervical cancer screening among adult women aged 21-65 years',
       'Fair or poor self-rated health status among adults aged >=18 years',
       'Older adult women aged >=65 years who are up to date on a core set of clinical preventive services: Flu shot past year, PPV shot ever, Colorectal cancer screening, and Mammogram past 2 years'],
      dtype=object)

In [450]:
places_2023.groupby('Year').count()

,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Data_Value_Footnote_Symbol,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
Year,,,,,,,,,,,,,,,,,,,,
2020,455534,455534,455534,455534,455534,455534,455534,455534,447213,8321,8321,447213,447213,455534,455534,455534,455534,455534,455534,455534
2021,1599234,1599234,1599234,1599234,1599234,1599234,1599234,1599234,1569016,30218,30218,1569016,1569016,1599234,1599234,1599234,1599234,1599234,1599234,1599234

In [451]:
diabetes_2021=places_2023.loc[(places_2023['Year']==2021)&(places_2023['Measure']=='Diagnosed diabetes among adults aged >=18 years')&(places_2023['Data_Value_Type']=='Crude prevalence')]

In [452]:
diabetes2021_percent=pd.DataFrame()

In [453]:
for i in state_list:
    diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())

C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3776226626.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  diabetes2021_percent=diabetes2021_percent.append(diabetes_2021.loc[(diabetes_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())

In [454]:
diabetes2021_percent=diabetes2021_percent.sort_values('StateAbbr')

In [455]:
diabetes2021_percent=diabetes2021_percent.reset_index().rename(columns={'StateAbbr':'State', 'Data_Value':'Percent_diabetes'})

In [456]:
diabetes2021_percent

   State  Percent_diabetes
0     AK         11.854237
1     AL         14.262565
2     AR         13.329588
3     AZ         13.652619
4     CA         11.142663
5     CO          8.613426
6     CT          9.090141
7     DC          8.100000
8     DE         10.985714
9     GA         13.593098
10    HI          9.670470
11    IA         10.022129
12    ID         10.856944
13    IL         10.291882
14    IN         11.298225
15    KS         11.540571
16    KY         12.294413
17    LA         13.877801
18    MA          8.511066
19    MD         10.636791
20    ME         10.052308
21    MI         10.333478
22    MN          9.667808
23    MO         11.916155
24    MS         15.012155
25    MT         10.776812
26    NC         12.983743
27    ND         10.866877
28    NE         10.641065
29    NH          8.458763
30    NJ          9.339372
31    NM         14.661244
32    NV         11.625203
33    NY         10.082704
34    OH         11.655894
35    OK         13.503112
36    OR         10.918750
37    PA         10.033524
38    RI          8.963889
39    SC         14.446329
40    SD         11.209851
41    TN         13.233100
42    TX         13.373650
43    UT          9.137618
44    VA         11.627150
45    VT          8.561157
46    WA          9.776471
47    WI          9.067526
48    WV         14.800746
49    WY          9.658242

In [463]:
heart_2021=places_2023.loc[(places_2023['Year']==2021)&(places_2023['Measure']=='Coronary heart disease among adults aged >=18 years')&(places_2023['Data_Value_Type']=='Crude prevalence')]

In [465]:
heart2021_percent=pd.DataFrame()

In [466]:
for i in state_list:
    heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())

C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\3957433715.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  heart2021_percent=heart2021_percent.append(heart_2021.loc[(heart_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())

In [467]:
heart2021_percent=heart2021_percent.sort_values('StateAbbr')

In [468]:
heart2021_percent=heart2021_percent.reset_index().rename(columns={'StateAbbr':'State', 'Data_Value':'Percent_coronary'})

In [ ]:
Current lack of health insurance among adults aged 18-64 years'

In [555]:
uninsured_2021=places_2023.loc[(places_2023['Year']==2021)&(places_2023['Measure']=='Current lack of health insurance among adults aged 18-64 years')&(places_2023['Data_Value_Type']=='Crude prevalence')]

In [557]:
ins2021_percent=pd.DataFrame()

In [558]:
for i in state_list:
    ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())

C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())
C:\Users\Evan\AppData\Local\Temp\ipykernel_15344\2812279409.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ins2021_percent=ins2021_percent.append(uninsured_2021.loc[(uninsured_2021['StateDesc']==i), ('Data_Value', 'StateAbbr')].groupby('StateAbbr').mean())

In [560]:
ins2021_percent=ins2021_percent.sort_values('StateAbbr')

In [562]:
ins2021_percent=ins2021_percent.reset_index().rename(columns={'StateAbbr':'State', 'Data_Value':'Percent_uninsured'})

In [563]:
ins2021_percent

   State  Percent_uninsured
0     AK          14.265763
1     AL          12.523744
2     AR          11.195880
3     AZ          15.024286
4     CA          10.871739
5     CO          11.570370
6     CT           6.440141
7     DC           6.500000
8     DE           9.516883
9     GA          17.926645
10    HI           6.240940
11    IA           7.517850
12    ID          10.741667
13    IL           8.158007
14    IN           8.787130
15    KS          10.412995
16    KY           7.637616
17    LA          11.002960
18    MA           4.080328
19    MD           8.335029
20    ME           8.029231
21    MI           7.659855
22    MN           6.932078
23    MO          13.192025
24    MS          14.677624
25    MT           9.044348
26    NC          13.731831
27    ND           7.458675
28    NE           7.891255
29    NH           7.530928
30    NJ           9.601294
31    NM          12.356459
32    NV          10.756911
33    NY           5.969353
34    OH           8.093652
35    OK          12.950212
36    OR           8.387500
37    PA           7.537236
38    RI           5.925000
39    SC          15.096456
40    SD           9.246269
41    TN          12.699767
42    TX          24.855490
43    UT           9.922571
44    VA           8.226138
45    VT           7.089256
46    WA           8.831863
47    WI           6.987758
48    WV          10.058706
49    WY          12.294505

In [471]:
health_data2021=heart2021_percent.merge(diabetes2021_percent, how='inner', on='State')

In [472]:
health_data2021=health_data2021.merge(stroke2021_percent, how='inner', on='State')

In [564]:
health_data2021=health_data2021.merge(ins2021_percent, how='inner', on='State')

In [565]:
health_data2021

,State,Percent_coronary,Percent_diabetes,Percent_stroke,Percent_uninsured
0,AK,6.678305,11.854237,3.833898,14.265763
1,AL,7.591508,14.262565,4.043328,12.523744
2,AR,8.130524,13.329588,4.077715,11.195880
3,AZ,7.907143,13.652619,4.352857,15.024286
4,CA,5.898438,11.142663,3.144973,10.871739
5,CO,5.398611,8.613426,2.847917,11.570370
6,CT,5.496479,9.090141,2.809155,6.440141
7,DC,3.700000,8.100000,2.900000,6.500000
8,DE,6.257143,10.985714,3.266234,9.516883
9,GA,6.650883,13.593098,3.912681,17.926645
10,HI,5.083893,9.670470,2.991946,6.240940
11,IA,6.461378,10.022129,3.264823,7.517850
12,ID,6.607870,10.856944,3.335648,10.741667
13,IL,6.146863,10.291882,3.144723,8.158007
14,IN,6.511095,11.298225,3.256509,8.787130
15,KS,7.245325,11.540571,3.412361,10.412995
16,KY,7.491061,12.294413,3.642644,7.637616
17,LA,7.065751,13.877801,4.076110,11.002960
18,MA,5.663525,8.511066,2.805738,4.080328
19,MD,5.454795,10.636791,3.039922,8.335029
20,ME,7.190769,10.052308,3.353846,8.029231
21,MI,6.750435,10.333478,3.396377,7.659855
22,MN,6.280708,9.667808,3.151598,6.932078
23,MO,7.267485,11.916155,3.623108,13.192025
24,MS,7.374033,15.012155,4.387017,14.677624
25,MT,6.924348,10.776812,3.582319,9.044348
26,NC,7.226639,12.983743,3.958470,13.731831
27,ND,7.250789,10.866877,3.516719,7.458675
28,NE,6.807985,10.641065,3.392015,7.891255
29,NH,5.623711,8.458763,2.881443,7.530928
30,NJ,5.622736,9.339372,2.848614,9.601294
31,NM,7.183493,14.661244,3.910766,12.356459
32,NV,7.126829,11.625203,3.563415,10.756911
33,NY,5.968430,10.082704,2.892107,5.969353
34,OH,6.996373,11.655894,3.338829,8.093652
35,OK,7.798586,13.503112,3.916549,12.950212
36,OR,7.091033,10.918750,3.505707,8.387500
37,PA,6.715705,10.033524,3.306910,7.537236
38,RI,5.863889,8.963889,2.897222,5.925000
39,SC,6.932152,14.446329,3.981519,15.096456
40,SD,7.255821,11.209851,3.630149,9.246269
41,TN,7.629604,13.233100,3.756876,12.699767
42,TX,6.599050,13.373650,3.478872,24.855490
43,UT,5.173354,9.137618,2.766144,9.922571
44,VA,6.128668,11.627150,3.423103,8.226138
45,VT,6.066116,8.561157,3.057025,7.089256
46,WA,5.737092,9.776471,3.125163,8.831863
47,WI,6.194201,9.067526,3.130670,6.987758
48,WV,9.167164,14.800746,4.037065,10.058706
49,WY,6.031868,9.658242,3.017582,12.294505

In [478]:
math_2022_4=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/data/Math_2022_4.csv')

In [480]:
math_2022_4=math_2022_4.drop(columns=['SigSymbol'])

In [483]:
math_2022_4th=math_2022_4.rename(columns={'Jurisdiction':'State', 'MN':'avg_math_4th', 'SigDiff':'diff_math_4th', 'AB':'math_AB_4th', 'AP':'math_AP_4th'})

In [484]:
math_2022_4th

    State  avg_math_4th  diff_math_4th  math_AB_4th math_AP_4th
0   DoDEA           250             15           92          51
1      WY           243              8           84          44
2      MA           242              7           79          43
3      NE           242              7           80          43
4      FL           241              6           81          41
5      WI           240              5           79          43
6      ND           240              5           81          40
7      IA           240              5           80          40
8      UT           240              5           78          42
9      NH           239              5           80          40
10     NJ           239              4           77          39
11     IN           239              4           78          40
12     MN           239              4           78          41
13     SD           239              4           80          40
14     TX           239              4           78          38
15     MN           239              4           80          38
16     OH           238              3           76          40
17     PA           238              3           76          40
18     IL           237              2           76          38
19     HI           237              2           77          37
20     VA           236              1           75          38
21     CT           236              1           74          37
22     TN           236              1           76          36
23     ID           236              1           76          36
24     CO           236              1           75          36
25     NC           236              1           75          35
26     KS           235              0           75          35
27     WA           235              0           74          35
28     GA           235              0           75          34
29     US           235              0           74          35
30     VT           234             -1           74          34
31     SC           234             -1           74          34
32     RI           234             -1           74          34
33     KY           234             -1           75          33
34     MS           234             -1           74          32
35     ME           233             -2           75          32
36     MO           232             -2           72          34
37     MI           232             -3           71          32
38     AZ           232             -3           70          32
39     CA           230             -4           67          30
40     AL           230             -5           71          27
41     OK           229             -5           71          27
42     NV           229             -6           69          28
43     MD           229             -6           65          31
44     LA           229             -6           69          27
45     OR           228             -7           66          29
46     AR           228             -7           69          28
47     NY           227             -8           66          28
48     WV           226             -9           67          23
49     AK           226             -9           65          28
50     DE           226             -9           64          26
51     DC           223            -12           57          24
52     NM           221            -14           60          19
53     PR           178            -57           10           #

In [520]:
reading_2022_4th=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/data/Reading_2022_4.csv')

In [521]:
reading_2022_4th=reading_2022_4th.drop(columns=['SigSymbol'])

In [522]:
reading_2022_4th=reading_2022_4th.rename(columns={'Jurisdiction':'State', 'MN':'avg_read_4th', 'SigDiff':'diff_read_4th', 'AB':'read_AB_4th', 'AP':'read_AP_4th'})

In [523]:
reading_2022_4th

   State  avg_read_4th  diff_read_4th  read_AB_4th  read_AP_4th
0     MA           227             11           70           43
1     WY           225              9           71           38
2     FL           225              9           71           39
3     CO           223              7           68           38
4     NJ           223              7           67           38
5     NH           223              6           67           37
6     UT           221              5           67           37
7     CT           219              3           64           35
8     PA           219              3           64           34
9     HI           219              3           64           35
10    MT           219              3           65           34
11    NE           219              3           65           34
12    OH           219              2           65           35
13    SD           218              2           65           32
14    IA           218              2           64           33
15    IL           218              2           62           33
16    ND           218              1           65           31
17    WI           217              1           63           33
18    IN           217              1           63           33
19    RI           217              1           62           34
20    MS           217              1           63           31
21    VT           217              1           62           34
22    WA           217              1           61           34
23    KY           217              0           62           31
24    SC           216              0           61           32
25    NC           216              0           61           32
26    US           216              0           61           32
27    GA           216              0           61           32
28    AZ           215             -1           61           31
29    MN           215             -1           61           32
30    ID           215             -1           61           32
31    KS           215             -1           60           31
32    CA           214             -2           58           31
33    TX           214             -2           58           30
34    VA           214             -2           60           32
35    TN           214             -2           59           30
36    NY           214             -3           58           30
37    MO           213             -3           60           30
38    AL           213             -3           59           28
39    ME           213             -3           60           29
40    MD           212             -4           56           31
41    LA           212             -4           57           28
42    AR           212             -4           58           30
43    MI           212             -4           58           28
44    NV           212             -5           57           27
45    OR           210             -6           56           28
46    DE           208             -8           53           25
47    OK           208             -8           55           24
48    DC           207             -9           50           26
49    WV           205            -11           52           22
50    AK           204            -12           51           24
51    NM           202            -14           48           21

In [517]:
reading_2022_8th=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/data/Reading_2022_8.csv')

In [518]:
reading_2022_8th=reading_2022_8th.drop(columns=['SigSymbol'])

In [534]:
reading_2022_4th.dtypes

State            object
avg_read_4th      int64
diff_read_4th     int64
read_AB_4th       int64
read_AP_4th       int64
dtype: object

In [533]:
reading_2022_8th.dtypes

Jurisdiction    object
MN               int64
SigDiff          int64
AB               int64
AP               int64
dtype: object

In [536]:
reading_2022_8th=reading_2022_8th.rename(columns={'Jurisdiction':'State', 'MN':'avg_read_8th', 'SigDiff':'diff_read_8th', 'AB':'read_AB_8th', 'AP':'read_AP_8th'})

In [545]:
math_2022_8th=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/data/Math_2022_8.csv')

In [550]:
math_2022_8th=math_2022_8th.drop(columns=['SigSymbol'])

In [551]:
math_2022_8th=math_2022_8th.rename(columns={'Jurisdiction':'State', 'MN':'avg_math_8th', 'SigDiff':'diff_math_8th', 'AB':'math_AB_8th', 'AP':'math_AP_8th'})

In [552]:
math_2022_8th

   State  avg_math_8th  diff_math_8th  math_AB_8th  math_AP_8th
0     MA           284             10           70           35
1     UT           282              9           70           35
2     ID           282              9           71           32
3     SD           281              8           72           32
4     WI           281              8           70           33
5     WY           281              8           72           31
6     NJ           281              8           67           33
7     MN           280              7           69           32
8     NE           279              6           68           31
9     VA           279              6           65           31
10    IN           279              6           66           30
11    NH           279              5           70           29
12    ND           278              5           69           28
13    MT           277              4           68           29
14    IA           277              4           67           28
15    CT           276              3           63           30
16    VT           276              3           66           27
17    WA           276              3           64           28
18    OH           276              3           64           29
19    IL           275              2           62           27
20    CO           275              2           63           28
21    PA           274              1           62           27
22    NY           274              1           60           28
23    NC           274              1           61           25
24    US           273              0           60           26
25    TX           273              0           61           24
26    MI           273             -1           60           25
27    ME           273             -1           61           24
28    MO           272             -1           61           24
29    TN           272             -1           60           25
30    KS           272             -1           61           23
31    GA           271             -2           59           24
32    FL           271             -2           58           23
33    AZ           271             -2           58           24
34    RI           270             -3           58           24
35    OR           270             -3           57           22
36    HI           270             -3           58           22
37    AK           270             -3           59           23
38    CA           270             -3           56           23
39    KY           269             -4           57           21
40    NV           269             -4           56           21
41    SC           269             -4           56           22
42    MD           269             -4           54           25
43    AR           267             -6           55           19
44    LA           266             -8           53           19
45    MS           266             -8           54           18
46    AL           264             -9           53           19
47    DE           264             -9           51           18
48    OK           264             -9           52           16
49    WV           260            -13           48           15
50    DC           260            -14           46           16
51    NM           259            -14           45           13

In [566]:
big_df2=health_data2021.merge(reading_2022_4th, how='right', left_on='State', right_on='State')

In [567]:
big_df2=big_df2.merge(reading_2022_8th, how='left', on='State')

In [568]:
big_df2=big_df2.merge(math_2022_4th, how='left', on='State')

In [569]:
big_df2=big_df2.merge(math_2022_8th, how='left', on='State')

In [597]:
big_df2=big_df2.merge(vax_df, how='left', on='State')

In [601]:
big_df2=big_df2.merge(school_perc, how='left', on='State')

In [603]:
big_df2.to_csv('healthschool_data_2021.csv')

In [604]:
big_df2

,State,Percent_coronary,Percent_diabetes,Percent_stroke,Percent_uninsured,avg_read_4th,diff_read_4th,read_AB_4th,read_AP_4th,avg_read_8th,...,math_AB_8th,math_AP_8th,Percentage_MMR,Percent_pneumococcal,Percentage_HepB,Percentage_HPV,Percent_elem,Percent_High,Percent_mid,Percent_unaccounted
0,MA,5.663525,8.511066,2.805738,4.080328,227,11,70,43,269,...,70,35,97.0,71.2,95.9,75.0,57.073,20.108,17.507,5.312
1,WY,6.031868,9.658242,3.017582,12.294505,225,9,71,38,261,...,72,31,91.3,66.8,89.1,48.0,53.297,24.725,16.758,5.220
2,FL,NaN,NaN,NaN,NaN,225,9,71,39,260,...,58,23,95.2,NaN,95.7,49.0,52.144,22.170,13.780,11.906
3,CO,5.398611,8.613426,2.847917,11.570370,223,7,68,38,263,...,63,28,95.6,76.3,93.8,69.2,54.229,22.574,14.946,8.251
4,NJ,5.622736,9.339372,2.848614,9.601294,223,7,67,38,270,...,67,33,90.0,64.2,91.5,54.8,58.418,18.862,16.758,5.962
5,NH,5.623711,8.458763,2.881443,7.530928,223,6,67,37,263,...,70,29,97.2,75.1,96.9,72.3,57.460,19.153,20.161,3.226
6,UT,5.173354,9.137618,2.766144,9.922571,221,5,67,37,265,...,70,35,93.1,73.4,94.3,61.4,56.244,17.610,12.668,13.478
7,CT,5.496479,9.090141,2.809155,6.440141,219,3,64,35,264,...,63,30,96.2,72.9,96.4,66.4,60.340,19.680,17.882,2.098
8,PA,6.715705,10.033524,3.306910,7.537236,219,3,64,34,259,...,62,27,92.7,70.3,92.6,68.7,55.556,24.289,17.751,2.404
9,HI,5.083893,9.670470,2.991946,6.240940,219,3,64,35,259,...,58,22,91.6,60.4,93.8,69.3,62.373,14.576,14.237,8.814
10,MT,6.924348,10.776812,3.582319,9.044348,219,3,65,34,261,...,68,29,94.2,69.3,91.2,52.6,51.628,20.869,27.141,0.362
11,NE,6.807985,10.641065,3.392015,7.891255,219,3,65,34,259,...,68,31,94.0,75.3,92.9,61.9,49.816,24.770,11.786,13.628
12,OH,6.996373,11.655894,3.338829,8.093652,219,2,65,35,262,...,64,29,95.0,70.7,94.1,62.2,50.340,25.510,18.658,5.492
13,SD,7.255821,11.209851,3.630149,9.246269,218,2,65,32,262,...,72,32,98.0,74.2,97.2,74.7,45.429,27.008,23.407,4.156
14,IA,6.461378,10.022129,3.264823,7.517850,218,2,64,33,260,...,67,28,97.7,75.4,97.6,66.1,52.101,25.745,19.099,3.055
15,IL,6.146863,10.291882,3.144723,8.158007,218,2,62,33,262,...,62,27,96.0,70.9,96.1,62.2,53.490,21.852,16.423,8.235
16,ND,7.250789,10.866877,3.516719,7.458675,218,1,65,31,258,...,69,28,98.3,70.4,93.1,72.2,51.224,31.073,7.910,9.793
17,WI,6.194201,9.067526,3.130670,6.987758,217,1,63,33,262,...,70,33,98.6,71.8,95.2,63.3,50.000,24.889,17.848,7.263
18,IN,6.511095,11.298225,3.256509,8.787130,217,1,63,33,261,...,66,30,92.5,73.1,92.9,55.2,55.521,21.504,17.403,5.572
19,RI,5.863889,8.963889,2.897222,5.925000,217,1,62,34,259,...,58,24,94.8,74.6,96.3,83.2,55.732,20.701,18.790,4.777
20,MS,7.374033,15.012155,4.387017,14.677624,217,1,63,31,253,...,54,18,92.3,63.2,91.0,32.7,42.418,30.326,17.850,9.406
21,VT,6.066116,8.561157,3.057025,7.089256,217,1,62,34,264,...,66,27,97.1,70.6,94.1,66.7,68.197,20.656,8.525,2.622
22,WA,5.737092,9.776471,3.125163,8.831863,217,1,61,34,262,...,64,28,93.2,75.4,90.6,67.8,48.664,26.047,15.078,10.211
23,KY,7.491061,12.294413,3.642644,7.637616,217,0,62,31,258,...,57,21,94.6,65.9,94.9,57.0,47.258,28.851,14.360,9.531
24,SC,6.932152,14.446329,3.981519,15.096456,216,0,61,32,254,...,56,22,95.3,70.9,95.0,62.1,54.062,22.656,19.609,3.673
25,NC,7.226639,12.983743,3.958470,13.731831,216,0,61,32,256,...,61,25,95.3,75.2,95.5,67.8,54.396,21.575,17.802,6.227
26,US,NaN,NaN,NaN,NaN,216,0,61,32,259,...,60,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,GA,6.650883,13.593098,3.912681,17.926645,216,0,61,32,260,...,59,24,95.5,70.2,95.9,60.9,56.772,19.602,20.640,2.986
28,AZ,7.907143,13.652619,4.352857,15.024286,215,-1,61,31,259,...,58,24,86.4,69.1,86.2,61.7,48.669,30.323,9.355,11.653
29,MN,6.280708,9.667808,3.151598,6.932078,215,-1,61,32,260,...,69,32,95.2,71.0,96.1,65.7,38.749,36.310,12.628,12.313
30,MN,6.280708,9.667808,3.151598,6.932078,215,-1,61,32,260,...,69,32,95.2,71.0,96.1,65.7,38.749,36.310,12.628,12.313
31,ID,6.607870,10.856944,3.335648,10.741667,215,-1,61,32,264,...,71,32,89.2,68.3,90.8,61.6,49.052,25.917,14.412,10.619
32,KS,7.245325,11.540571,3.412361,10.412995,215,-1,60,31,256,...,61,23,94.6,74.4,93.1,64.3,55.267,26.183,17.099,1.451
33,CA,5.898438,11.142663,3.144973,10.871739,214,-2,58,31,259,...,56,23,89.3,65.4,90.5,69.0,57.783,21.607,13.650,6.960
34,TX,6.599050,13.373650,3.478872,24.855490,214,-2,58,30,255,...,61,24,84.1,69.0,84.4,51.5,49.741,19.436,18.517,12.306
35,VA,6.128668,11.627150,3.423103,8.226138,214,-2,60,32,260,...,65,31,94.8,75.0,92.2,64.9,53.850,15.258,16.291,14.601
36,TN,7.629604,13.233100,3.756876,12.699767,214,-2,59,30,258,...,60,25,95.1,69.9,95.1,56.5,54.468,21.489,18.989,5.054
37,NY,5.968430,10.082704,2.892107,5.969353,214,-3,58,30,262,...,60,28,94.2,65.6,96.2,64.4,53.053,24.488,16.746,5.713
38,MO,7.267485,11.916155,3.623108,13.192025,213,-3,60,30,258,...,61,24,88.3,72.9,90.7,59.3,49.715,26.992,16.138,7.155
39,AL,7.591508,14.262565,4.043328,12.523744,213,-3,59,28,251,...,53,19,95.8,70.1,92.4,62.5,45.093,26.235,16.485,12.187
40,ME,7.190769,10.052308,3.353846,8.029231,213,-3,60,29,257,...,61,24,94.9,72.4,92.5,61.5,58.638,19.601,14.120,7.641
41,MD,5.454795,10.636791,3.039922,8.335029,212,-4,56,31,259,...,54,25,94.8,74.4,93.2,71.9,62.562,16.890,16.115,4.433
42,LA,7.065751,13.877801,4.076110,11.002960,212,-4,57,28,257,...,53,19,94.1,69.5,91.8,63.9,53.250,20.384,16.691,9.675
43,AR,8.130524,13.329588,4.077715,11.195880,212,-4,58,30,255,...,55,19,94.0,70.7,94.1,56.8,47.685,27.870,19.352,5.093
44,MI,6.750435,10.333478,3.396377,7.659855,212,-4,58,28,259,...,60,25,88.9,72.0,90.6,64.7,46.665,28.202,14.298,10.835
45,NV,7.126829,11.625203,3.563415,10.756911,212,-5,57,27,259,...,56,21,90.3,64.3,89.9,56.5,56.499,19.629,15.517,8.355
46,OR,7.091033,10.918750,3.505707,8.387500,210,-6,56,28,257,...,57,22,92.4,75.5,92.7,67.0,56.453,21.219,16.152,6.176
47,DE,6.257143,10.985714,3.266234,9.516883,208,-8,53,25,253,...,51,18,92.5,72.8,91.0,68.9,51.739,18.261,16.087,13.913
48,OK,7.798586,13.503112,3.916549,12.950212,208,-8,55,24,251,...,52,16,91.8,75.3,90.4,56.7,52.179,26.089,20.391,1.341
49,DC,3.700000,8.100000,2.900000,6.500000,207,-9,50,26,250,...,46,16,87.8,72.2,85.6,79.4,60.851,17.021,17.447,4.681
50,WV,9.167164,14.800746,4.037065,10.058706,205,-11,52,22,249,...,48,15,87.6,72.0,86.1,56.4,57.806,22.644,15.612,3.938
51,AK,6.678305,11.854237,3.833898,14.265763,204,-12,51,24,253,...,59,23,91.8,64.4,90.5,56.2,33.792,15.324,7.466,43.418
52,NM,7.183493,14.661244,3.910766,12.356459,202,-14,48,21,248,...,45,13,88.1,68.6,88.0,57.9,51.580,24.718,18.510,5.192

In [339]:
Df2122=pd.DataFrame()